---
- name: Binaries
  hosts: app
  run_once: true
  tasks:
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/app/build-and-check.yaml
      vars:
        maven_phase: package
