---
- name: SOURCES
  hosts: java
  tasks:
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/java/check.yaml

- name: BINARIES
  hosts: tool
  tasks:
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/binary/capture.yaml
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/binary/build-check-publish.yaml
      vars:
        maven_phase: install

- name: BINARIES
  hosts: lib
  tasks:
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/binary/capture.yaml
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/binary/build-check-publish.yaml
      vars:
        maven_phase: "{{ 'deploy' if repo_mode == 'rw' else 'install' }}"

- name: BINARIES
  hosts: app
  tasks:
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/binary/capture.yaml
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/binary/build-check-publish.yaml
      vars:
        maven_phase: "{{ app_phase | default('package') }}"
    - name: Coverage
      ansible.builtin.command:
        cmd: >-
          mvn clean
            antrun:run@coverage
            --no-snapshot-updates
            --batch-mode
            --projects :tool
        chdir: "{{ project.dir }}"
        strip_empty_ends: false
      changed_when: true
