---
- name: Building and checking
  hosts: app
  tasks:
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/java/check.yaml
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/app/build-and-check.yaml
      vars:
        maven_phase: package
