---
- name: Checking
  hosts: java
  run_once: true
  tasks:
    - name: Analyze
      ansible.builtin.command:
        cmd: >-
          mvn clean
            enforcer:enforce
            spotless:check
            pmd:check
            compiler:compile
            spotbugs:check
            --activate-profiles {{ devenv }}
            --no-snapshot-updates
            --batch-mode
        chdir: "{{ project.dir }}"
        strip_empty_ends: false
      changed_when: true

- name: Checking
  hosts: ansible
  run_once: true
  tasks:
    - name: Linting
      ansible.builtin.command:
        # list all top level playbooks
        cmd: ansible-lint sources.yaml binaries.yaml stacks.yaml
        strip_empty_ends: false
      changed_when: true

- name: Checking
  hosts: github
  run_once: true
  tasks:
    - name: Linting
      ansible.builtin.command:
        cmd: yamllint {{ project.dir }}/.github
        strip_empty_ends: false
      changed_when: true
