---
- name: Sources
  hosts: java
  run_once: true
  tasks:
    - name: Analyze
      ansible.builtin.command:
        cmd: >-
          mvn
          --no-snapshot-updates
          --batch-mode
          enforcer:enforce
          spotless:check
          pmd:check
          compiler:compile
          spotbugs:check
          --define maven.compiler.release={{ dev[devenv].jdk.release }}
        chdir: "{{ project.dir }}"
        strip_empty_ends: false
      changed_when: false

- name: Sources
  hosts: ansible
  run_once: true
  tasks:
    - name: Analyze
      ansible.builtin.command:
        # list all top level playbooks
        cmd: >-
          ansible-lint
          sources.yaml
          stacks.yaml
        strip_empty_ends: false
      changed_when: false

- name: Sources
  hosts: github
  run_once: true
  tasks:
    - name: Analyze
      ansible.builtin.command:
        cmd: yamllint {{ project.dir }}/.github
        strip_empty_ends: false
      changed_when: false
