---
- import_playbook: images.yaml  # noqa: name[play]
  tags: [images, deps]

- name: Capturing
  hosts: stack
  tasks:
    - ansible.builtin.include_tasks:  # noqa: name[missing]
        file: tasks/{{ inventory_hostname }}/capture.yaml
        apply:
          tags: [always]
      tags: [always]

- name: Building
  hosts: gear
  run_once: true
  tasks:
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/gear/build.yaml
      tags: [build]
      when: >-
        hostvars.gear.stack_status is changed and
        hostvars.gear.is_virtual.rc != 0

- name: Building & Checking
  hosts: product
  run_once: true
  vars:
    stack_dir: "{{ project.dir }}/stack/product"
  tasks:
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/product/build.yaml
      tags: [build]
      when: >-
        hostvars.product.stack_status is changed or
        hostvars.gear.stack_status is changed
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/product/check.yaml
      tags: [check]
      when: >-
        hostvars.product.stack_status is changed or
        hostvars.gear.stack_status is changed

- name: Publishing
  hosts: stack
  tasks:
    - ansible.builtin.include_tasks:  # noqa: name[missing]
        file: tasks/{{ inventory_hostname }}/publish.yaml
        apply:
          tags: [publish]
      tags: [publish]
      when: hostvars[inventory_hostname].stack_status is changed
