---
- import_playbook: images.yaml  # noqa: name[play]

- name: STACKS
  hosts: stacks
  tasks:
    - ansible.builtin.include_tasks:  # noqa: name[missing]
        file: tasks/{{ inventory_hostname }}/capture.yaml
        apply:
          tags: [always]
      tags: [always]

- name: GEAR
  hosts: gear
  tasks:
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/ansible/check.yaml
      tags: [build]
      when: stack_status is changed
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/gear/build.yaml
      tags: [build]
      when: >-
        stack_status is changed and
        is_virtual.rc != 0

- name: PIPELINE
  hosts: pipeline
  tasks:
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/yaml/check.yaml
      tags: [build]
      when: stack_status is changed

- name: PRODUCT
  hosts: product
  vars:
    stack_dir: "{{ project.dir }}/stack/product"
  tasks:
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/product/build.yaml
      tags: [build]
      when: >-
        hostvars.product.stack_status is changed or
        hostvars.gear.stack_status is changed
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/product/check.yaml
      tags: [check]
      when: >-
        hostvars.product.stack_status is changed or
        hostvars.gear.stack_status is changed

- name: STACKS
  hosts: stacks
  tasks:
    - ansible.builtin.include_tasks:  # noqa: name[missing]
        file: tasks/{{ inventory_hostname }}/publish.yaml
        apply:
          tags: [publish]
      tags: [publish]
      when: hostvars[inventory_hostname].stack_status is changed
