---
- name: Remove stand (or part of it)
  ansible.builtin.command:
    cmd: docker rm -f env-db
  changed_when: false
  when: hostvars.db.image_status|default({}) is changed

- name: Create network
  ansible.builtin.shell:
    cmd: docker network inspect gear || docker network create gear
    strip_empty_ends: false
  changed_when: false

- name: Create stand
  ansible.builtin.command:
    cmd: >-
      docker compose
        --file compose.yaml
        --profile {{ opsenv }}
        up
        --remove-orphans
        --quiet-pull
        --no-deps
        --detach
    chdir: "{{ stack_dir }}/target/image-context"
    strip_empty_ends: false
  changed_when: true

- name: Test stand
  ansible.builtin.command:
    cmd: >-
      mvn clean test
        --activate-profiles {{ devenv }}
        --no-snapshot-updates
        --batch-mode
        --threads 2
        --projects :e2e
        --also-make
        --define skipUnits
      {% if hostvars.gear.is_virtual.rc == 0 %}
        --define testing.client.host=sepuling
      {% endif %}
      {% if modulus is defined %}
        --define testing.sharding.modulus={{ modulus }}
      {% endif %}
      {% if reminder is defined %}
        --define testing.sharding.reminder={{ reminder }}
      {% endif %}
    chdir: "{{ project.dir }}"
    strip_empty_ends: false
  changed_when: true
