---
- name: Remove artifacts
  ansible.builtin.file:
    path: "{{ stack_dir }}/target"
    state: absent

- ansible.builtin.import_role:  # noqa: name[missing]
    name: image
    tasks_from: clean
  vars:
    image_keys:
      - "{{ product.image }}/{{ opsenv }}"
