---
- ansible.builtin.import_role:  # noqa: name[missing]
    name: image
    tasks_from: publish
  vars:
    image_source_tag: "{{ product.image }}:{{ opsenv }}"
    image_target_tags:
      - "{{ image_ns }}/{{ product.image }}:{{ hostvars.product.stack_tag }}"
