version: '3'

set: [pipefail]

vars:
  STAND_TOY_REVISION:
    sh: git write-tree --prefix=stands/toy
  STAND_TOY_REV: '{{.STAND_TOY_REVISION | trunc 7}}'

tasks:
  mk:
    run: once
    env:
      REGISTRY: '{{.REGISTRY}}'
      SCHEMA_TAG: '{{.LIB_SCHEMA_REV}}'
      FOO_TAG: '{{.APP_FOO_REV}}'
    cmds:
      # deps
      - task: ::lib:schema:image
      - task: ::app:foo:image
      # wipes
      - task: wipe-db
      # actions
      - cmd: >
          docker compose
          --profile {{.DB_VENDOR}}
          up
          --detach
  test:
    run: once
    cmds:
      # deps
      - task: mk
      # actions
      - cmd: >
          mvn clean test
  wipe:
    run: once
    env:
      REGISTRY: '{{.REGISTRY}}'
      SCHEMA_TAG: '{{.LIB_SCHEMA_REV}}'
      FOO_TAG: '{{.APP_FOO_REV}}'
    cmds:
      - cmd: >
          docker compose
          --profile {{.DB_VENDOR}}
          down
          --volumes
  wipe-db:
    run: once
    internal: true
    status:
      - docker inspect schema-owner-{{.LIB_SCHEMA_REV}}
    cmds:
      - docker rm -f env-db
