version: '3'

vars:
  STAND_TOY_REVISION:
    sh: git write-tree --prefix=stands/toy
  STAND_TOY_CID: '{{.STAND_TOY_REVISION | trunc 7}}'
  STAND_TOY_IMAGE: '{{.PROJECT_REPO}}/{{.PROJECT_NAME}}-stand-toy'
  STAND_TOY_REF: '{{.STAND_TOY_IMAGE}}:{{.STAND_TOY_CID}}'

tasks:
  image:
    run: once
    internal: true
    status:
      - docker image {{.COMMAND}} {{.STAND_TOY_REF}}
    cmds:
      - task: ::docker:image:reset
        vars:
          IMAGE: '{{.STAND_TOY_IMAGE}}'
      - cmd: >
          docker build .
          -f Dockerfile
          -t {{.STAND_TOY_REF}}
      - task: ::docker:image:push
        vars:
          REF: '{{.STAND_TOY_REF}}'
