version: '3'

set: [pipefail]

vars:
  STAND_TOY_REVISION:
    sh: git write-tree --prefix=stands/toy
  STAND_TOY_REV: '{{.STAND_TOY_REVISION | trunc 7}}'

tasks:
  mk:
    run: once
    env:
      REGISTRY: '{{.REGISTRY}}'
      LIBS_SCHEMA_TAG: '{{.LIBS_SCHEMA_REV}}'
      FOO_TAG: '{{.APP_FOO_REV}}'
    cmds:
      # deps
      - task: ::lib:schema:image
      - task: ::app:foo:image
      # actions
      - cmd: >
          docker compose
          --profile {{.DB_VENDOR}}
          up
          --detach
  test:
    run: once
    cmds:
      # deps
      - task: mk
      # actions
      - cmd: >
          mvn clean test
  rm:
    run: once
    env:
      REGISTRY: '{{.REGISTRY}}'
      LIBS_SCHEMA_TAG: '{{.LIBS_SCHEMA_REV}}'
      FOO_TAG: '{{.APP_FOO_REV}}'
    cmds:
      - cmd: >
          docker compose
          --profile {{.DB_VENDOR}}
          down
          --volumes
