version: '3'

set: [pipefail]

vars:
  STAND_TOY_REVISION:
    sh: git write-tree --prefix=stands/toy
  STAND_TOY_CID: '{{.STAND_TOY_REVISION | trunc 7}}'
  STAND_TOY_IMAGE: 'stand-toy'
  STAND_TOY_REPO: '{{.PROJECT_REPO}}/{{.STAND_TOY_IMAGE}}'
  STAND_TOY_REF: '{{.STAND_TOY_REPO}}:{{.STAND_TOY_CID}}'

env:
  SCHEMA_CID: '{{.LIB_SCHEMA_CID}}'
  SCHEMA_IMAGE: '{{.LIB_SCHEMA_IMAGE}}'
  SCHEMA_REPO: '{{.LIB_SCHEMA_REPO}}'
  SCHEMA_REF: '{{.LIB_SCHEMA_REF}}'
  FOO_CID: '{{.APP_FOO_CID}}'
  FOO_IMAGE: '{{.APP_FOO_IMAGE}}'
  FOO_REPO: '{{.APP_FOO_REPO}}'
  FOO_REF: '{{.APP_FOO_REF}}'

tasks:
  image:
    run: once
    vars:
      COMMAND: '{{if eq .REGISTRY "localhost"}}inspect{{else}}pull{{end}}'
    status:
      - docker image {{.COMMAND}} {{.STAND_TOY_REF}}
    cmds:
      - task: reset
      - cmd: >
          docker build .
          -f Dockerfile
          -t {{.STAND_TOY_REF}}
  run:
    run: once
    cmds:
      # deps
      - task: ::lib:schema:image
      - task: ::app:foo:image
      - task: image
      # wipes
      - task: wipe-db
      # actions
      - cmd: >
          docker compose
          --profile {{.ENV_DB_VENDOR}}
          up
          --detach
  wipe:
    run: once
    cmds:
      - cmd: >
          docker compose
          --profile {{.ENV_DB_VENDOR}}
          down
          --volumes
  wipe-db:
    run: once
    internal: true
    status:
      - docker inspect schema-owner-{{.LIB_SCHEMA_CID}}
    cmds:
      - docker rm -f env-db
  reset:
    run: once
    internal: true
    cmds:
      - cmd: docker rmi -f $(docker images -q -f reference={{.STAND_TOY_REPO}}) 2> /dev/null
        ignore_error: true
