version: '3'

tasks:
  image:
    run: once
    internal: true
    status:
      - docker {{.ENTITY}} inspect {{.STAND_TOY_REF}}
    cmds:
      - task: ::docker:image:reset
        vars:
          IMAGE: '{{.STAND_TOY_IMAGE}}'
      - cmd: >
          docker build .
          -f Dockerfile
          -t {{.STAND_TOY_REF}}
      - task: ::docker:image:push
        vars:
          REF: '{{.STAND_TOY_REF}}'
