version: '3'

vars:
  USAGE: toy
  VENDOR: postgres
  REVISION:
    sh: git write-tree --prefix=env/db
  REV: '{{.REVISION | trunc 7 }}'

tasks:
  empty:
    desc: create empty database for specific usage
    vars:
      NAME: '{{.USAGE}}-{{.VENDOR}}-{{.REV }}'
    status:
      - docker container inspect {{.NAME}}
    dir: src
    cmds:
      - cmd: docker rm -f $(docker ps -aq -f name={{.USAGE}}-{{.VENDOR}}*)
        ignore_error: true
      - cmd: ansible-playbook db.yml -i toy -e container_name={{.NAME}}
