---
- name: Build
  ansible.builtin.command:
    cmd: >-
      mvn {{ maven_phase|mandatory }}
        --activate-profiles {{ devenv }}
        --no-snapshot-updates
        --batch-mode
        --fail-fast
        --also-make
        --threads 2
      {% if image_status is defined %}
        --projects {{
          image_status.results
          | select('changed')
          | map(attribute='app')
          | map('regex_replace', '^', ':')
          | join(',')
        }}
      {% else %}
        --projects {{
          product.apps.values()
          | flatten
          | map(attribute='name')
          | map('regex_replace', '^', ':')
          | join(',')
        }}
      {% endif %}
    chdir: "{{ project.dir }}"
    strip_empty_ends: false
  changed_when: true

- name: Analyze coverage
  ansible.builtin.command:
    cmd: >-
      mvn clean
        antrun:run@coverage
        --no-snapshot-updates
        --batch-mode
        --projects :tool
    chdir: "{{ project.dir }}"
    strip_empty_ends: false
  changed_when: true
