---
- ansible.builtin.include_role:  # noqa: name[missing]
    name: image
    tasks_from: publish
  vars:
    source_tag: "{{ app.image }}:{{ devenv }}"
    target_tags:
      - "{{ image_ns }}/{{ app.image }}:{{ hostvars.app.image_tags[app.binary] }}"
  loop: "{{ hostvars.app.image_status.results|select('changed')|map(attribute='app') }}"
  loop_control:
    loop_var: app
    label: "{{ app.image }}"
