version: '3'

tasks:
  run:
    run: once
    cmds:
      - task: ::lib:images
      - task: ::app:images
      - task: ::stand:images
      - task: ::test:images
#      - task: ::test:image
#        vars:
#          TEST_TYPE: toy
#      - task: ::test:image
#        vars:
#          TEST_TYPE: func
