version: '3'

set: [pipefail]

tasks:
  image:
    run: once
    status:
      - docker image {{.COMMAND}} {{.SCHEMA_PG_REF}}
    cmds:
      - task: ::docker:image:reset
        vars:
          IMAGE: '{{.SCHEMA_PG_IMAGE}}'
      - cmd: docker build . -t {{.SCHEMA_PG_REF}}
      - task: ::docker:image:push
        vars:
          REF: '{{.SCHEMA_PG_REF}}'
