---
- name: Remove artifacts
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../solutions/target"
    state: absent

- name: Create directories
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../solutions/target/context"
    state: directory
    recurse: true

- name: Build spec
  vars:
    config_files:
      turing: application.yaml
      church: application.conf
    config_mapping_modes:
      turing: spring_config
      church: lightbend_config
  ansible.builtin.command:
    cmd: >
      docker compose
      --file basis/compose.yml
      --file {{ usage }}/compose.yml
      --profile {{ prefs }}
      config
      --output target/context/compose.yml
      --no-path-resolution
    strip_empty_ends: false
    chdir: "{{ playbook_dir }}/../solutions"
  environment:
    SCHEMA_TAG: "{{ schema_cids.postgres }}"
    SCHEMA_IMAGE: "{{ schema_images.postgres }}"
    FOO_TAG: "{{ hostvars.app.image_cids.foo[:7] }}"
    FOO_IMAGE: "{{ app_images.foo }}"
    CONFIG_FILE_NAME: "{{ config_files[prefs] }}"
    CONFIG_MAPPING_MODE: "{{ config_mapping_modes[prefs] }}"
  changed_when: true

- name: Build conf
  vars:
    config_extensions:
      turing: yaml
      church: conf
  ansible.builtin.command:
    cmd: >
      cp basis/{{ prefs }}.{{ config_extensions[prefs] }}
      target/context/application.{{ config_extensions[prefs] }}
    chdir: "{{ playbook_dir }}/../solutions"
  changed_when: true
