---
- name: Remove artifacts
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../solutions/target"
    state: absent

- name: Create directories
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../solutions/target/context"
    state: directory
    recurse: true

- name: Build spec
  ansible.builtin.command:
    cmd: >
      docker compose
      --file basis/compose.yml
      --file {{ usage }}/compose.yml
      --profile {{ prefs }}
      config
      --output target/context/compose.yml
      --no-path-resolution
    strip_empty_ends: false
    chdir: "{{ playbook_dir }}/../solutions"
  environment:
    SCHEMA_TAG: "{{ schema_cid }}"
    SCHEMA_IMAGE: "{{ schema_images.postgres }}"
    FOO_TAG: "{{ hostvars.app.image_cid.stdout[:7] }}"
    FOO_IMAGE: "{{ app_images.foo }}"
  changed_when: true

- name: Build conf
  ansible.builtin.command:
    cmd: cp basis/{{ prefs }}.conf target/context/bezmen.conf
    chdir: "{{ playbook_dir }}/../solutions"
  changed_when: true
