---
- name: Capture tag
  ansible.builtin.command:
    cmd: git hash-object --stdin
    stdin: |
      {{ lib_cid }}
      {{ app_cid }}
      {{ schema_cid }}
      {{ solution_cid }}
      {{ test_cid }}
  register: solution_tag
  changed_when: false

- name: Capture status
  ansible.builtin.command:
    cmd: docker {{ docker_entity }} inspect {{ solution_image }}:{{ solution_tag.stdout[:7] }}
  register: solution_status
  changed_when:
    - capture_solution|bool
    - solution_status.rc != 0
  failed_when: false

- name: Status command
  ansible.builtin.debug:
    msg: "{{ solution_status.cmd|join(' ') }}"
  when: solution_status is changed
