---
- name: Capture cid
  ansible.builtin.command:
    cmd: git hash-object --stdin
    stdin: |
      {{ lib_cid }}
      {{ app_cid }}
      {{ schema_cid }}
      {{ solution_cid }}
  register: stack_cid
  changed_when: false

- name: Capture status
  ansible.builtin.command:
    cmd: docker {{ docker_entity }} inspect {{ stack_images.solution }}:{{ stack_cid.stdout[:7] }}-{{ opsenv }}
  register: stack_status
  changed_when:
    - stack_status.rc != 0
  failed_when: false

- name: Status command
  ansible.builtin.debug:
    msg: "{{ stack_status.cmd|join(' ') }}"
  when: stack_status is changed
