---
- name: Capture cid
  ansible.builtin.command:
    cmd: git hash-object --stdin
    stdin: |
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=libs')[:7] }}
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=apps')[:7] }}
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=databases')[:7] }}
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=stacks/solution')[:7] }}
  register: stack_cid
  changed_when: false

- name: Capture status
  ansible.builtin.command:
    cmd: docker {{ docker_entity }} inspect {{ solution.image.name }}:{{ stack_cid.stdout[:7] }}-{{ opsenv }}
  register: stack_status
  changed_when:
    - stack_status.rc != 0
  failed_when: false

- name: Status command
  ansible.builtin.debug:
    msg: "{{ stack_status.cmd|join(' ') }}"
  when: stack_status is changed
