version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/libs"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/apps"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/tests"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/tools"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/schemas/postgres"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/apps/foo"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
