---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
    groups:
      spring-framework:
        patterns:
          - "org.springframework*"
      junit-platform:
        patterns:
          - "org.junit*"
      jetbrains-kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/setup-gear"
    schedule:
      interval: "weekly"
    groups:
      docker:
        patterns:
          - "docker/*"
  - package-ecosystem: "docker"
    directory: "/db/postgres"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/stack/gear/env/church"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/stack/gear/env/church"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/stack/gear/env/turing"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: "pip"
    directory: "/stack/gear/env/godel"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
