---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/libs"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    groups:
      SpringFramework:
        patterns:
          - "org.springframework*"
  - package-ecosystem: "maven"
    directory: "/apps"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "smecalculus.bezmen:*"
  - package-ecosystem: "maven"
    directory: "/tests"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "smecalculus.bezmen:*"
  - package-ecosystem: "maven"
    directory: "/tools"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/schemas/postgres"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/apps/foo"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/.environs/green"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/.environs/amber"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
