---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    groups:
      spring-framework:
        patterns:
          - "org.springframework*"
  - package-ecosystem: "docker"
    directory: "/schemas/postgres"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/apps/sepuling"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/.environs/green"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/.environs/amber"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
