---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/libs"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/apps"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.smecalculus.bezmen:*"
  - package-ecosystem: "maven"
    directory: "/tests"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.smecalculus.bezmen:*"
  - package-ecosystem: "maven"
    directory: "/tools"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/schemas/postgres"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/apps/foo"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/.env/green"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/.env/amber"
    schedule:
      interval: "weekly"
