---
# todo: think about backward compatibility aspect
- name: Remove stand (or part of it)
  ansible.builtin.command:
    cmd: docker rm -f env-db
  when: hostvars.schema.image_status|default({}) is changed

- name: Create stand
  ansible.builtin.command:
    cmd: >
      docker compose
      --file compose.yml
      --profile {{ props }}
      up
      --remove-orphans
      --quiet-pull
      --no-deps
      --detach
    chdir: "{{ playbook_dir }}/../stacks/target/context"
    strip_empty_ends: false
  changed_when: true

- name: Test stand
  ansible.builtin.command:
    cmd: >
      mvn
      --no-snapshot-updates
      --batch-mode
      --projects e2e
      --activate-profiles {{ usage }}
      --define lib.version={{ lib_version }}
      clean
      test
      --define props.combo={{ props }}
      {% if reminder is defined %}
      --define bezmen.sharding.reminder={{ reminder }}
      {% endif %}
      {% if modulus is defined %}
      --define bezmen.sharding.modulus={{ modulus }}
      {% endif %}
    chdir: "{{ playbook_dir }}/../tests"
    strip_empty_ends: false
  changed_when: true
