---
- ansible.builtin.import_role:  # noqa: name[missing]
    name: image
    tasks_from: publish
  vars:
    image_source_tag: "{{ pipeline.image }}:{{ devenv }}"
    image_target_tags:
      - "{{ image_ns }}/{{ pipeline.image }}:{{ hostvars.pipeline.stack_tag }}"
