= bezmen

Шаблон репозитория backend-проекта на Java.

== Планы CI/CD

Планы делим на 2 категории:

. Проверяющие решение (solution), которое мы реализуем для клиентов
. Проверяющие конвейер (pipeline), который мы реализуем для разработчиков

=== Проверка решения

Решение проверяем во всех окружениях, в которых его могут эксплуатировать клиенты.

==== Минимальная (minimal)

Запускаем линтеры, статический анализ и компиляцию для исходного кода решения.

==== В пределах разумного (reasonable)

Все перечисленное ранее. Плюс запускаем модульные тесты, анализируем покрытие и собираем бинарники.

==== Убедительная (convincing)

Все перечисленное ранее. Плюс запускаем интеграционные тесты и собираем пакеты (например, docker-образы).

==== За пределами сомнений (beyond doubt)

Все перечисленное ранее. Плюс запускаем сквозные тесты, собираем и публикуем стеки.

=== Проверка конвейера

Конвейер проверяем во всех окружениях, в которых его могут эксплуатировать разработчики.

==== Минимальная (minimal)

Запускаем линтеры для исходного кода конвейера.

==== За пределами сомнений (beyond doubt)

Запускаем весь конвейер на минимальном наборе тестов.

== CLI

    ansible-playbook <object>.yml [-l <selector>]

== Todo

. Релизная сборка
. Версионирование библиотек и приложений (взглянуть критически)
. Агрегация отчетов покрытия (взглянуть критически)
. Локальные проверки в удаленном репозитории
. Чистка пакетов в удаленном репозитории
. Поддержка нескольких версий JDK
