version: '3'

vars:
  PROJECT_NAME: bezmen
  REGISTRY: localhost
  PROJECT_REPO: '{{.REGISTRY}}/smecalculus'
  USAGE: '{{.USAGE | default "toy"}}'
  PROPS: '{{.PROPS | default "turing"}}'
  GIT_ADD_ALL:
    sh: git add -A
  ENV_DB_VENDOR: postgres
  ENTITY: '{{if eq .REGISTRY "localhost"}}image{{else}}manifest{{end}}'
  COMMAND: '{{if eq .REGISTRY "localhost"}}inspect{{else}}pull{{end}}'

includes:
  lib:
    taskfile: libs/Taskfile.yml
    dir: libs
  schema:
    taskfile: schemas/Taskfile.yml
    dir: schemas
  app:
    taskfile: apps/Taskfile.yml
    dir: apps
  stand:
    taskfile: stands/Taskfile.yml
    dir: stands
  test:
    taskfile: tests/Taskfile.yml
    dir: tests
  stage:
    taskfile: stages/Taskfile.yml
    dir: stages
  docker:
    taskfile: tools/Taskfile.docker.yml
    dir: tools
  coverage:
    taskfile: tools/Taskfile.coverage.yml
    dir: tools

tasks:
  sources:
    aliases: [source, code]
    cmds:
      - task: lib:sources
      - task: app:sources
      - task: test:sources
  binaries:
    aliases: [binary]
    cmds:
      - task: lib:binaries
      - task: app:binaries
      - task: test:binaries
  images:
    aliases: [image]
    cmds:
      - task: lib:images
      - task: app:images
      - task: stand:images
      - task: schema:images
      - task: test:images
  units:
    aliases: [unit]
    cmds:
      - task: lib:units
      - task: app:units
      - task: coverage:units
  integrations:
    aliases: [integration]
    cmds:
      - task: lib:integrations
      - task: app:integrations
      - task: coverage:integrations
  stands:
    cmds:
      - task: stand:toy:run
      - task: stand:func:run
