version: '3'

includes:
  app:
    taskfile: app/Taskfile.yml
    dir: app
  lib:
    taskfile: lib/Taskfile.yml
    dir: lib
  env:
    taskfile: env/Taskfile.yml
    dir: env

tasks:
  cleanup:
    cmds:
      - docker image prune -f
      - docker volume prune -f
      - docker network prune -f
