version: '3'

vars:
  DB_VENDOR: postgres
  REGISTRY: localhost
  ROOT_REVISION:
    sh: git add -A && git write-tree

includes:
  lib:
    taskfile: libs/Taskfile.yml
    dir: libs
  env:
    taskfile: env/Taskfile.yml
    dir: env
  app:
    taskfile: apps/Taskfile.yml
    dir: apps
  stand:
    taskfile: stands/Taskfile.yml
    dir: stands
  test:
    taskfile: tests/Taskfile.yml
    dir: tests

tasks:
  clean:
    cmds:
      - docker image prune -f
      - docker volume rm $(docker volume ls -q -f dangling=true)
      - docker network prune -f
