version: '3'

vars:
  DB_MODE: postgres

includes:
  lib:
    taskfile: lib/Taskfile.yml
    dir: lib
  env:
    taskfile: env/Taskfile.yml
    dir: env
  app:
    taskfile: app/Taskfile.yml
    dir: app
  stand:
    taskfile: stand/Taskfile.yml
    dir: stand
  test:
    taskfile: test/Taskfile.yml
    dir: test

tasks:
  clean:
    cmds:
      - docker image prune -f
      - docker volume prune -f
      - docker network prune -f
