version: '3'

vars:
  DB_MODE: postgres

includes:
  app:
    taskfile: app/Taskfile.yml
    dir: app
  lib:
    taskfile: lib/Taskfile.yml
    dir: lib
  env:
    taskfile: env/Taskfile.yml
    dir: env
  stand:
    taskfile: stand/Taskfile.yml
    dir: stand

tasks:
  clean:
    cmds:
      - docker image prune -f
      - docker volume prune -f
      - docker network prune -f
