---
lib_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=libs')[:7] }}"
app_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=apps')[:7] }}"
schema_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=schemas')[:7] }}"
solution_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=solutions')[:7] }}"

environ: green

dx_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=.dx')[:7] }}"
environ_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=.environ/' ~ environ)[:7] }}"
tool_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=.tools')[:7] }}"
test_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=tests')[:7] }}"

lib_version: 0.1.0-{{ lib_cid }}
app_version: 0.1.0-{{ app_cid }}

usage: toy
prefs: turing

# solution - focus on solution changes
# pipeline - focus on pipeline changes
# none - without any particular focus
focus: none

maven_host: local
docker_host: local

docker_repo: smecalculus
docker_entity: "{{ 'image' if docker_host == 'local' else 'manifest' }}"

schema_images:
  postgres: "{{ docker_host }}/{{ docker_repo }}/schema-postgres"
app_images:
  foo: "{{ docker_host }}/{{ docker_repo }}/app-foo"
solution_image: "{{ docker_host }}/{{ docker_repo }}/solution-{{ usage }}-{{ prefs }}"
pipeline_image: "{{ docker_host }}/{{ docker_repo }}/pipeline-{{ environ }}"
