name: bezmen

services:
  db:
    image: postgres:15-alpine
    container_name: env-db
    profiles:
      - turing
      - church
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bezmen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  schema-dba:
    image: ${SCHEMA_REF}
    container_name: schema-dba-${SCHEMA_CID}
    profiles:
      - turing
      - church
    depends_on:
      db:
        condition: service_healthy
    labels:
      bezmen.image: ${SCHEMA_IMAGE}
      bezmen.revision: ${SCHEMA_CID}
    command: >
      --show-banner=false
      --changelog-file=alfa/dba/changelog.yml
      --url=jdbc:postgresql://db:5432/bezmen?currentSchema=public
      --liquibase-schema-name=public
      --username=postgres
      --password=password
      --labels=user,schema
      update
      -Dbezmen.schema=bezmen
      -Dbezmen.owner=bezmen
      -Dbezmen.password=bezmen
  schema-owner:
    image: ${SCHEMA_REF}
    container_name: schema-owner-${SCHEMA_CID}
    profiles:
      - turing
      - church
    depends_on:
      schema-dba:
        condition: service_completed_successfully
    labels:
      bezmen.image: ${SCHEMA_IMAGE}
      bezmen.revision: ${SCHEMA_CID}
    command: >
      --show-banner=false
      --changelog-file=alfa/owner/changelog.yml
      --url=jdbc:postgresql://db:5432/bezmen?currentSchema=bezmen
      --liquibase-schema-name=bezmen
      --username=bezmen
      --password=bezmen
      update
  foo:
    image: ${FOO_REF}
    container_name: app-foo
    ports:
      - "8080:8080"
    volumes:
      - ./all.conf:/home/bezmen/app/all.conf
      - ./${PROPS_COMBO}.conf:/home/bezmen/app/application.conf
    depends_on:
      schema-owner:
        condition: service_completed_successfully
    labels:
      bezmen.image: ${FOO_IMAGE}
      bezmen.revision: ${FOO_CID}
