- name: postgres
  hosts: all
  gather_facts: no
  tasks:
    - community.docker.docker_container:
        name: "{{ container_name }}"
        image: postgres:15-alpine
        network_mode: host
        state: started
        healthcheck:
          test: ["CMD-SHELL", "pg_isready"]
          interval: 10s
          timeout: 5s
          retries: 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bezmen
