---
- name: Codebase
  hosts: java
  run_once: true
  tasks:
    - name: Analyze
      ansible.builtin.command:
        cmd: >-
          mvn
          --no-snapshot-updates
          --batch-mode
          enforcer:enforce
          spotless:check
        chdir: "{{ project.dir }}"
        strip_empty_ends: false
      changed_when: false

- name: Codebase
  hosts: ansible
  run_once: true
  tasks:
    - name: Analyze
      ansible.builtin.command:
        # list all top level playbooks
        cmd: >-
          ansible-lint
          toolchain.yaml
          codebase.yaml
          stacks.yaml
        strip_empty_ends: false
      changed_when: false

- name: Codebase
  hosts: github
  run_once: true
  tasks:
    - name: Analyze
      ansible.builtin.command:
        cmd: yamllint {{ project.dir }}/.github
        strip_empty_ends: false
      changed_when: false
