---
- name: Toolchain
  hosts: toolchain
  run_once: true
  vars:
    docker: "{{ dev[devenv].docker|default(dev.anyone.docker) }}"
  tasks:
    - name: Capture docker version
      ansible.builtin.command:
        cmd: docker version --format {{'{{.Server.Version}}'}}
      register: docker_version
      changed_when: false
    - name: Check docker version
      ansible.builtin.assert:
        quiet: true
        that:
          - docker_version.stdout is version(docker.min, '>=', version_type='semver')
          - docker_version.stdout is version(docker.max, '<', version_type='semver')
        msg: "{{ docker.min }} <= docker < {{ docker.max }}"

- name: Capturing
  hosts: toolchain
  run_once: true
  tasks:
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/toolchain/status.yaml
      tags: [always]

- name: Building
  hosts: toolchain
  run_once: true
  vars:
    stack_dir: "{{ project.dir }}/stacks/toolchain"
  tasks:
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/toolchain/build.yaml
      tags: [build]
      when: stack_status is changed
