---
name: Setup gear
description: Setup gear
inputs:
  devenv:
    description: Env name
    required: true
  token:
    description: Github token
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cat /etc/docker/daemon.json | jq '. + {"userns-remap": "runner"}' | sudo tee /etc/docker/daemon.json
        sudo sed -i -e "1i runner:$(getent group docker | cut -d: -f3):1" /etc/subgid
        sudo sed -i -e "1i runner:$(id -u):1" /etc/subuid
        sudo systemctl restart docker
        docker network create gear
    - uses: docker/setup-buildx-action@v3.1.0
    - uses: docker/build-push-action@v5.2.0
      with:
        context: stack/gear/env/${{ inputs.devenv }}
        tags: stack/gear:${{ inputs.devenv }}
        load: true
        cache-from: type=gha,scope=stack/gear/${{ inputs.devenv }}
        cache-to: type=gha,mode=max,scope=stack/gear/${{ inputs.devenv }}
    - uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    # for the sake of maven setup & dependency caching
    - uses: actions/setup-java@v4.1.0
      with:
        distribution: 'temurin'
        java-version: '21'
        check-latest: false
        cache: 'maven'
        cache-dependency-path: |
          pom.xml
          lib/pom.xml
          tool/pom.xml
