---
toolchain:
  image:
    name: "{{ image_repo }}/stack/toolchain"

app_name: "sepuling-{{ ops[opsenv].runtime.lang }}"

solution:
  name: "{{ project_name }}"
  cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=stacks/solution')[:7] }}"
  image:
    name: "{{ image_repo }}/stack/solution-{{ usecase }}"
  config:
    file_name: "application.{{ config_exts[ops[opsenv].config.mapping_mode] }}"
    mapping_mode: "{{ ops[opsenv].config.mapping_mode }}"
  storage: "{{ ops[opsenv].storage }}"
  database:
    name: "{{ project_name }}"
  schemas:
    sepulkarium:
      name: sepulkarium
      image:
        name: "{{ image_repo }}/schema/{{ ops[opsenv].storage.vendor }}"
        tag: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=schemas/' ~ ops[opsenv].storage.vendor)[:7] }}"
      owner:
        name: "{{ project_name }}"
        password: "{{ project_name }}"
  apps:
    sepuling:
      name: sepuling
      cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=apps/' ~ app_name)[:7] }}"
      binary:
        name: "{{ app_name }}"
      image:
        name: "{{ image_repo }}/app/{{ app_name }}"

config_exts:
  lightbend_config: conf
  spring_config: yaml
