---
toolchain:
  image:
    name: "{{ image_repo }}/stack/toolchain"

solution:
  name: "{{ project.name }}"
  cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=stacks/solution')[:7] }}"
  image:
    name: "{{ image_repo }}/stack/solution-{{ aim }}"
  config:
    file_name: "application.{{ config_exts[ops[opsenv].config.mapping_mode] }}"
    mapping_mode: "{{ ops[opsenv].config.mapping_mode }}"
  storages:
    postgres:
      image: "docker.io/library/postgres"
      dba:
        username: "postgres"
        password: "password"
      owner:
        username: "{{ project.name }}"
        password: "{{ project.name }}"
  databases:
    postgres:
      name: "{{ project.name }}"
      cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=databases/postgres')[:7] }}"
      image: "{{ image_repo }}/database/postgres"
  schemas:
    postgres:
      - name: sepulkarium
  apps:
    java:
      - service: sepuling
        image: "{{ image_repo }}/app/sepuling-java"
        binary: sepuling-java
    kotlin:
      - service: sepuling
        image: "{{ image_repo }}/app/sepuling-kotlin"
        binary: sepuling-kotlin

config_exts:
  lightbend_config: conf
  spring_config: yaml
