---
- name: Capture CID
  ansible.builtin.command:
    cmd: git hash-object --stdin
    stdin: |
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=tool') }}
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=test') }}
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=orchestrator') }}
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=stack/gear/env/' ~ devenv) }}
  register: stack_cid
  changed_when: false

- name: Declare tag
  ansible.builtin.set_fact:
    stack_tag: "{{ devenv }}-{{ stack_cid.stdout[:7] }}"
  changed_when: false

- name: Capture statuses
  ansible.builtin.command:
    cmd: docker {{ docker_entity }} inspect {{ image_ns }}/{{ item }}
  register: stack_status
  failed_when: false
  changed_when:
    - stack_status.rc != 0
  loop:
    - "{{ gear.image }}:{{ stack_tag }}"

- name: Capture env
  ansible.builtin.command:
    cmd: test -f /.dockerenv
  register: is_virtual
  changed_when: false
  failed_when: false
