---
- ansible.builtin.import_role:  # noqa: name[missing]
    name: image
  vars:
    image_tag: "{{ stack_cid.stdout[:7] }}-{{ devenv }}"
    image_name: "{{ toolchain.image.name }}"
    image_home: "{{ playbook_dir }}/../.github"
    image_context: .
    image_push: "{{ image_storage != 'local' }}"
