version: '3'

set: [pipefail]

vars:
  STAGE_VERIFICATION_STATUS: verified

tasks:
  run:
    run: once
    status:
      - docker {{.ENTITY}} inspect {{.LIB_SCHEMA_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - docker {{.ENTITY}} inspect {{.APP_FOO_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - docker {{.ENTITY}} inspect {{.STAND_BASIS_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - docker {{.ENTITY}} inspect {{.STAND_TOY_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - docker {{.ENTITY}} inspect {{.STAND_FUNC_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - docker {{.ENTITY}} inspect {{.TEST_TOY_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - docker {{.ENTITY}} inspect {{.TEST_FUNC_REF}}-{{.STAGE_VERIFICATION_STATUS}}
    preconditions:
      - docker image {{.COMMAND}} {{.LIB_SCHEMA_REF}}
      - docker image {{.COMMAND}} {{.APP_FOO_REF}}
      - docker image {{.COMMAND}} {{.STAND_BASIS_REF}}
      - docker image {{.COMMAND}} {{.STAND_TOY_REF}}
      - docker image {{.COMMAND}} {{.STAND_FUNC_REF}}
      - docker image {{.COMMAND}} {{.TEST_TOY_REF}}
      - docker image {{.COMMAND}} {{.TEST_FUNC_REF}}
    cmds:
      - task: ::stand:run
      - task: ::lib:binaries
        vars:
          SKIP_TESTS: true
      - task: ::test:run
  transit:
    run: once
    preconditions:
      - docker image {{.COMMAND}} {{.LIB_SCHEMA_REF}}
      - docker image {{.COMMAND}} {{.APP_FOO_REF}}
      - docker image {{.COMMAND}} {{.STAND_BASIS_REF}}
      - docker image {{.COMMAND}} {{.STAND_TOY_REF}}
      - docker image {{.COMMAND}} {{.STAND_FUNC_REF}}
      - docker image {{.COMMAND}} {{.TEST_TOY_REF}}
      - docker image {{.COMMAND}} {{.TEST_FUNC_REF}}
    cmds:
      - docker tag {{.LIB_SCHEMA_REF}} {{.LIB_SCHEMA_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - task: ::docker:image:push
        vars:
          REF: '{{.LIB_SCHEMA_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - docker tag {{.APP_FOO_REF}} {{.APP_FOO_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - task: ::docker:image:push
        vars:
          REF: '{{.APP_FOO_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - docker tag {{.STAND_BASIS_REF}} {{.STAND_BASIS_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - task: ::docker:image:push
        vars:
          REF: '{{.STAND_BASIS_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - docker tag {{.STAND_TOY_REF}} {{.STAND_TOY_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - task: ::docker:image:push
        vars:
          REF: '{{.STAND_TOY_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - docker tag {{.STAND_FUNC_REF}} {{.STAND_FUNC_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - task: ::docker:image:push
        vars:
          REF: '{{.STAND_FUNC_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - docker tag {{.TEST_TOY_REF}} {{.TEST_TOY_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - task: ::docker:image:push
        vars:
          REF: '{{.TEST_TOY_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - docker tag {{.TEST_FUNC_REF}} {{.TEST_FUNC_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - task: ::docker:image:push
        vars:
          REF: '{{.TEST_FUNC_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
