version: '3'

set: [pipefail]

vars:
  STAGE_VERIFICATION_STATUS: verified

tasks:
  run:
    run: once
    vars:
      COMMAND: '{{if eq .REGISTRY "localhost"}}inspect{{else}}pull{{end}}'
    status:
      - docker image {{.COMMAND}} {{.LIB_SCHEMA_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - docker image {{.COMMAND}} {{.APP_FOO_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - docker image {{.COMMAND}} {{.STAND_X_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - docker image {{.COMMAND}} {{.TEST_X_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - '{{.LIB_BINARIES_STATUS}}'
    preconditions:
      - docker image {{.COMMAND}} {{.LIB_SCHEMA_REF}}
      - docker image {{.COMMAND}} {{.APP_FOO_REF}}
      - docker image {{.COMMAND}} {{.STAND_X_REF}}
      - docker image {{.COMMAND}} {{.TEST_X_REF}}
    cmds:
      - task: ::stand:run
      - task: ::lib:binaries
        vars:
          SKIP_TESTS: true
      - task: ::test:run
  transit:
    run: once
    cmds:
      - docker tag {{.TEST_TOY_REF}} {{.TEST_TOY_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - task: ::docker:image:push
        vars:
          DOCKER_IMAGE: '{{.TEST_TOY_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - docker tag {{.TEST_FUNC_REF}} {{.TEST_FUNC_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - task: ::docker:image:push
        vars:
          DOCKER_IMAGE: '{{.TEST_FUNC_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - docker tag {{.STAND_TOY_REF}} {{.STAND_TOY_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - task: ::docker:image:push
        vars:
          DOCKER_IMAGE: '{{.STAND_TOY_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - docker tag {{.STAND_FUNC_REF}} {{.STAND_FUNC_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - task: ::docker:image:push
        vars:
          DOCKER_IMAGE: '{{.STAND_FUNC_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - docker tag {{.APP_FOO_REF}} {{.APP_FOO_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - task: ::docker:image:push
        vars:
          DOCKER_IMAGE: '{{.APP_FOO_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - docker tag {{.LIB_SCHEMA_REF}} {{.LIB_SCHEMA_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - task: ::docker:image:push
        vars:
          DOCKER_IMAGE: '{{.LIB_SCHEMA_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
