version: '3'

set: [pipefail]

vars:
  STAGE_VERIFICATION_STATUS: verified

tasks:
  run:
    run: once
    status:
      - docker {{.ENTITY}} inspect {{.SCHEMA_PG_REF}}-{{.STAGE_VERIFICATION_STATUS}}
      - >
        for ref in {{.APP_USAGE_REFS}}; do
          docker {{.ENTITY}} inspect $ref-{{.STAGE_VERIFICATION_STATUS}}
        done
      - >
        for ref in {{.TEST_USAGE_REFS}}; do
          docker {{.ENTITY}} inspect $ref-{{.STAGE_VERIFICATION_STATUS}}
        done
      - >
        for ref in {{.STAND_USAGE_REFS}}; do
          docker {{.ENTITY}} inspect $ref-{{.STAGE_VERIFICATION_STATUS}}
        done
    cmds:
      - task: ::stand:run
        # TODO: ::lib:testing:binary
      - task: ::lib:binaries
        vars:
          SKIP_TESTS: true
      - task: ::test:run
  transit:
    run: once
    aliases: [ commit ]
    preconditions:
      - docker {{.ENTITY}} inspect {{.SCHEMA_PG_REF}}
      - docker {{.ENTITY}} inspect {{.APP_FOO_REF}}
      - docker {{.ENTITY}} inspect {{.STAND_BASIS_REF}}
      - docker {{.ENTITY}} inspect {{.STAND_TOY_REF}}
      - docker {{.ENTITY}} inspect {{.STAND_FUNC_REF}}
      - docker {{.ENTITY}} inspect {{.TEST_TOY_REF}}
      - docker {{.ENTITY}} inspect {{.TEST_FUNC_REF}}
    cmds:
      - task: ::docker:image:tag
        vars:
          OLD: '{{.SCHEMA_PG_REF}}'
          NEW: '{{.SCHEMA_PG_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - task: ::docker:manifest:push
        vars:
          REF: '{{.SCHEMA_PG_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - task: ::docker:image:tag
        vars:
          OLD: '{{.APP_FOO_REF}}'
          NEW: '{{.APP_FOO_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - task: ::docker:manifest:push
        vars:
          REF: '{{.APP_FOO_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - task: ::docker:image:tag
        vars:
          OLD: '{{.STAND_BASIS_REF}}'
          NEW: '{{.STAND_BASIS_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - task: ::docker:manifest:push
        vars:
          REF: '{{.STAND_BASIS_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - task: ::docker:image:tag
        vars:
          OLD: '{{.STAND_TOY_REF}}'
          NEW: '{{.STAND_TOY_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - task: ::docker:manifest:push
        vars:
          REF: '{{.STAND_TOY_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - task: ::docker:image:tag
        vars:
          OLD: '{{.STAND_FUNC_REF}}'
          NEW: '{{.STAND_FUNC_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - task: ::docker:manifest:push
        vars:
          REF: '{{.STAND_FUNC_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - task: ::docker:image:tag
        vars:
          OLD: '{{.TEST_TOY_REF}}'
          NEW: '{{.TEST_TOY_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - task: ::docker:manifest:push
        vars:
          REF: '{{.TEST_TOY_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - task: ::docker:image:tag
        vars:
          OLD: '{{.TEST_FUNC_REF}}'
          NEW: '{{.TEST_FUNC_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
      - task: ::docker:manifest:push
        vars:
          REF: '{{.TEST_FUNC_REF}}-{{.STAGE_VERIFICATION_STATUS}}'
