---
- name: Build, check, publish
  ansible.builtin.command:
    cmd: >-
      mvn {{ maven_phase | mandatory }}
        --activate-profiles {{ devenv }}
        --no-snapshot-updates
        --batch-mode
        --fail-fast
        --threads 2
        --projects {{ binary_modules.stdout_lines | map('regex_replace', '^', ':') | join(',') }}
      {% if repo_mode == 'rw' %}
        --define revision={{ binary_tag }}
      {% endif %}
    chdir: "{{ project.dir }}"
    strip_empty_ends: false
  changed_when: true
