---
- name: Check vars
  ansible.builtin.assert:
    quiet: true
    that:
      - image_name is defined
      - image_home is defined
      - image_key is defined

- name: Kill containers
  ansible.builtin.shell:
    cmd: docker container rm -f $(docker ps -aq --filter label=image.key={{ image_key }})
    strip_empty_ends: false
  changed_when: false
  failed_when: false
  no_log: true

- name: Remove outdated
  ansible.builtin.shell:
    cmd: docker image rm -f $(docker images -q --filter label=image.key={{ image_key }})
    strip_empty_ends: false
  changed_when: false
  failed_when: false
  no_log: true

- name: Build fresh
  ansible.builtin.command:
    cmd: >-
      docker build {{ image_context }} --file Dockerfile
      --tag {{ image_name }}:{{ image_tag }}
      --label image.key={{ image_key }}
      {% for key, value in image_args.items() %}
      --build-arg {{ key }}={{ value }}
      {% endfor %}
    chdir: "{{ image_home }}"
    strip_empty_ends: false
  changed_when: true

- name: Push built
  ansible.builtin.command:
    cmd: docker image push {{ image_name }}:{{ image_tag }}
    strip_empty_ends: false
  changed_when: true
  when: image_push|bool
