version: '3'

set: [pipefail]

vars:
  SCHEMA_DIR: src/main/resources/{{.DB_VENDOR}}
  SCHEMA_REVISION:
    sh: git write-tree --prefix=shared/schema/{{.SCHEMA_DIR}}
  SCHEMA_REV: '{{.SCHEMA_REVISION | trunc 7 }}'
  SCHEMA_IMAGE: '{{.REGISTRY}}/smecalculus/schema-{{.DB_VENDOR}}'

tasks:
  image-1:
    preconditions:
      - sh: '[ "{{.REGISTRY}}" = "localhost" ]'
#    vars:
#      SCHEMA_IMAGE: 'schema-{{.DB_VENDOR}}'
    status:
      - docker image inspect {{.SCHEMA_IMAGE}}:{{.SCHEMA_REV}}
    cmds:
      - task: reset
      - cmd: docker build . -t {{.SCHEMA_IMAGE}}:{{.SCHEMA_REV}}
    dir: '{{.SCHEMA_DIR}}'

  image-2:
    preconditions:
      - sh: '[ "{{.REGISTRY}}" != "localhost" ]'
#    vars:
#      SCHEMA_IMAGE: '{{.REGISTRY}}/smecalculus/schema-{{.DB_VENDOR}}'
    status:
      - docker pull {{.SCHEMA_IMAGE}}:{{.SCHEMA_REV}}
    cmds:
      - docker build . -t {{.SCHEMA_IMAGE}}:{{.SCHEMA_REV}}
      - docker push {{.SCHEMA_IMAGE}}:{{.SCHEMA_REV}}
    dir: '{{.SCHEMA_DIR}}'

  reset:
    internal: true
    cmds:
      - cmd: docker rm -f $(docker ps -aq -f label=ancestor={{.SCHEMA_IMAGE}}) 2> /dev/null
        ignore_error: true
      - cmd: docker rmi -f $(docker images -q --filter reference={{.SCHEMA_IMAGE}}*) 2> /dev/null
        ignore_error: true
