version: '3'

set: [pipefail]

vars:
  SCHEMA_DIR: src/main/resources/{{.DB_VENDOR}}
  SCHEMA_REVISION:
    sh: git write-tree --prefix=shared/schema/{{.SCHEMA_DIR}}
  SCHEMA_REV: '{{.SCHEMA_REVISION | trunc 7}}'
  SCHEMA_IMAGE: schema-{{.DB_VENDOR}}
  SCHEMA_REPO: '{{.REGISTRY}}/smecalculus/{{.SCHEMA_IMAGE}}'
  SCHEMA_REF: '{{.SCHEMA_REPO}}:{{.SCHEMA_REV}}'

tasks:
  image:
    vars:
      COMMAND: '{{if eq .REGISTRY "localhost"}}inspect{{else}}pull{{end}}'
    status:
      - docker image {{.COMMAND}} {{.SCHEMA_REF}}
    cmds:
      # deps
      - task: reset
      # actions
      - cmd: docker build . -t {{.SCHEMA_REF}}
    dir: '{{.SCHEMA_DIR}}'

  reset:
    internal: true
    cmds:
      - cmd: docker rm -f $(docker ps -aq -f label=bezmen.image={{.SCHEMA_IMAGE}}) 2> /dev/null
        ignore_error: true
      - cmd: docker rmi -f $(docker images -q -f reference={{.SCHEMA_REPO}}) 2> /dev/null
        ignore_error: true
