version: '3'

set: [pipefail]

vars:
  APP_FOO_REVISION:
    sh: git write-tree --prefix=apps/foo
  APP_FOO_CID: '{{.APP_FOO_REVISION | trunc 7}}'
  APP_FOO_VERSION: '{{.APP_VERSION}}-{{.APP_FOO_CID}}'
  APP_FOO_IMAGE: '{{.PROJECT}}-app-foo'
  APP_FOO_REPO: '{{.PROJECT_REPO}}/{{.APP_FOO_IMAGE}}'
  APP_FOO_REF: '{{.APP_FOO_REPO}}:{{.APP_FOO_CID}}'

tasks:
  binary:
    run: once
    status:
      - task --dir {{.ROOT_DIR}} --status lib:binary
      - test -f target/app-foo-{{.APP_FOO_VERSION}}.jar
    cmds:
      # deps
      - task: ::lib:binary
      # cmds
      - cmd: >
          mvn clean package -am -T1C
          -Drevision={{.APP_FOO_VERSION}}
          -Dlibs.version={{.LIBS_VERSION}}
  image:
    run: once
    vars:
      COMMAND: '{{if eq .REGISTRY "localhost"}}inspect{{else}}pull{{end}}'
    status:
      - task --dir {{.ROOT_DIR}} --status lib:binary
      - docker image {{.COMMAND}} {{.APP_FOO_REF}}
    cmds:
      # deps
      - task: binary
      # cmds
      - task: reset
      - cmd: >
          docker build target/docker-context
          -f Dockerfile
          -t {{.APP_FOO_REF}}
  reset:
    run: once
    internal: true
    cmds:
      - cmd: docker rm -f $(docker ps -aq -f label=bezmen.image={{.APP_FOO_IMAGE}}) 2> /dev/null
        ignore_error: true
      - cmd: docker rmi -f $(docker images -q -f reference={{.APP_FOO_REPO}}) 2> /dev/null
        ignore_error: true
