version: '3'

set: [pipefail]

tasks:
  binary:
    run: once
    status:
      - test -f target/app-foo-{{.APP_FOO_VERSION}}.jar
      - '{{.LIB_BINARIES_STATUS}}'
    cmds:
      # deps
      - task: ::lib:binaries
      # cmds
      - cmd: >
          mvn clean verify
          -am -T1C
          --batch-mode
          -Drevision={{.APP_FOO_VERSION}}
          -Dlibs.version={{.LIBS_VERSION}}
  image:
    run: once
    status:
      - docker image {{.COMMAND}} {{.APP_FOO_REF}}
      - '{{.LIB_BINARIES_STATUS}}'
    cmds:
      - task: binary
      - task: ::docker:image:reset
        vars:
          IMAGE: '{{.APP_FOO_IMAGE}}'
      - cmd: >
          docker build target/docker-context
          -f Dockerfile
          -t {{.APP_FOO_REF}}
      - task: ::docker:image:push
        vars:
          REF: '{{.APP_FOO_REF}}'
