---
- ansible.builtin.import_role:  # noqa: name[missing]
    name: image
  vars:
    image_tag: "{{ solution_tag }}"
    image_name: "{{ image_repo }}/{{ solution.image }}"
    image_home: "{{ project.dir }}/stack/solution"
    image_context: target/image-context
    image_key: "{{ solution.image }}:{{ purpose }}-{{ opsenv }}"
    image_push: "{{ image_storage != 'local' }}"
