---
- ansible.builtin.import_role:  # noqa: name[missing]
    name: image
    tasks_from: publish
  vars:
    image_source_tag: "tool/builder:{{ devenv }}"
    image_target_tags:
      - "{{ image_ns }}/tool/builder:{{ hostvars.tool.package_tag }}"
