version: '3'

set: [pipefail]

vars:
  REVISION:
    sh: git write-tree --prefix=app
  REV: '{{.REVISION | trunc 7 }}'

includes:
  foo:
    taskfile: foo/Taskfile.yml
    dir: foo

tasks:
  binary:
    # TODO
