version: '3'

set: [pipefail]

vars:
  REVISION:
    sh: git write-tree --prefix=app
  REV: '{{.REVISION | trunc 7 }}'
  VERSION: 0.1.0-{{.REV }}

tasks:
  binary:
    status:
      - test -f foo/target/foo-{{.VERSION}}.jar
    deps:
      - task: :lib:binary
    cmds:
      - find . -name "*.jar" -type f -delete
      - mvn package -am -T1C -Drevision={{.VERSION}}
