version: '3'

set: [pipefail]

vars:
  VENDOR: postgres
  IMAGE: schema-{{.VENDOR}}
  REGISTRY: '{{.REGISTRY | default "localhost" }}'
  BRANCH:
    sh: git rev-parse --abbrev-ref HEAD
  REVISION:
    sh: git write-tree --prefix=app/schema/{{.VENDOR}}
  REV: '{{.REVISION | trunc 7 }}'

tasks:
  binary-1:
    desc: create binary artifact
    preconditions:
      - sh: '[ "{{.REGISTRY}}" = "localhost" ]'
    status:
      - docker image inspect {{.IMAGE}}:{{.REV}}
    cmds:
      - docker build -t {{.IMAGE}}:{{.REV}} .
    dir: '{{.VENDOR}}'
  binary-2:
    desc: create binary artifact
    preconditions:
      - sh: '[ "{{.REGISTRY}}" != "localhost" ]'
    vars:
      NAME: '{{.REGISTRY}}/smecalculus/{{.IMAGE}}:{{.REV}}'
    status:
      - docker pull {{.NAME}}
    cmds:
      - docker build -t {{.NAME}} .
      - docker push {{.NAME}}
    dir: '{{.VENDOR}}'
  dba:
    desc: create dba objects
    vars:
      NAME: '{{.VENDOR}}-dba-{{.REV}}'
    status:
      - 'exit $(docker container inspect -f {{"{{.State.ExitCode}}"}} {{.NAME}} || echo 42)'
    deps:
      - task: binary
      - task: :db:empty
    cmds:
      - cmd: docker rm -f $(docker ps -aq --filter name={{.VENDOR}}-dba*) 2> /dev/null
        ignore_error: true
      - cmd: >
          docker run
          --name {{.NAME}}
          --net host
          {{.IMAGE}}:{{.REV}}
          --show-banner=false
          --changelog-file=dba/changelog.yml
          --url=jdbc:postgresql://localhost:5432/bezmen?currentSchema=public
          --liquibase-schema-name=public
          --username=postgres
          --password=password
          --labels=user,schema
          update
          -Dbezmen.schema=bezmen
          -Dbezmen.owner=bezmen
          -Dbezmen.password=bezmen
  owner:
    desc: create owner objects
    vars:
      NAME: '{{.VENDOR}}-owner-{{.REV}}'
    status:
      - 'exit $(docker container inspect -f {{"{{.State.ExitCode}}"}} {{.NAME}} || echo 42)'
    deps:
      - task: dba
    cmds:
      - cmd: docker rm -f $(docker ps -aq -f name={{.VENDOR}}-owner*) 2> /dev/null
        ignore_error: true
      - cmd: >
          docker run
          --name {{.NAME}}
          --net host
          {{.IMAGE}}:{{.REV}}
          --show-banner=false
          --changelog-file=owner/changelog.yml
          --url=jdbc:postgresql://localhost:5432/bezmen?currentSchema=bezmen
          --liquibase-schema-name=bezmen
          --username=bezmen
          --password=bezmen
          update
  reset:
      - cmd: docker rm -f $(docker ps -aq -f ancestor={{.IMAGE}}:{{.REV}})
        ignore_error: true
