---
organization: smecalculus
project: bezmen

devenv: turing
opsenv: lamport
usecase: toy

lib_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=libs')[:7] }}"
app_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=apps')[:7] }}"
app_cids:
  sepuling-java: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=apps/sepuling-java')[:7] }}"
  sepuling-kotlin: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=apps/sepuling-kotlin')[:7] }}"
schema_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=schemas')[:7] }}"
schema_cids:
  postgres: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=schemas/postgres')[:7] }}"
solution_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=solutions')[:7] }}"

test_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=tests')[:7] }}"

dx_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=.dx')[:7] }}"
env_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=envs')[:7] }}"
tool_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=tools')[:7] }}"
pipeline_cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=.github')[:7] }}"

binary_repo: local
image_repo: local

app_images:
  sepuling-java: "{{ image_repo }}/{{ organization }}/{{ project }}/app/sepuling-java"
  sepuling-kotlin: "{{ image_repo }}/{{ organization }}/{{ project }}/app/sepuling-kotlin"
schema_images:
  postgres: "{{ image_repo }}/{{ organization }}/{{ project }}/schema/postgres"
stack_images:
  solution: "{{ image_repo }}/{{ organization }}/{{ project }}/stack/solution-{{ usecase }}"
  toolchain: "{{ image_repo }}/{{ organization }}/{{ project }}/stack/toolchain"

docker_entity: "{{ 'image' if image_repo == 'local' else 'manifest' }}"

sepuling_deps: [abstraction, abstraction-client, essentials, messaging, messaging-client, storage]

app_deps:
  sepuling-java: "{{ sepuling_deps }}"
  sepuling-kotlin: "{{ sepuling_deps }}"
