---
solution:
  name: "{{ project_name }}"
  config:
    file_name: "application.{{ config_exts[ops[opsenv].config.mapping_mode] }}"
    mapping_mode: "{{ ops[opsenv].config.mapping_mode }}"
  storage: "{{ ops[opsenv].storage }}"
  database:
    name: "{{ project_name }}"
  schemas:
    - name: sepulkarium
      image:
        name: "{{ schema_images[ops[opsenv].storage.vendor] }}"
        tag: "{{ schema_cids[ops[opsenv].storage.vendor] }}"
      owner:
        name: "{{ project_name }}"
        password: "{{ project_name }}"
  apps:
    - name: sepuling
      image:
        name: "{{ app_images['sepuling-' ~ ops[opsenv].runtime.lang] }}"
        tag: "{{ hostvars.app.image_cids['sepuling-' ~ ops[opsenv].runtime.lang][:7] }}-{{ devenv }}"

config_exts:
  lightbend_config: conf
  spring_config: yaml
