---
- name: Check inputs
  ansible.builtin.assert:
    quiet: true
    that:
      - image_keys is defined

- name: Kill containers
  ansible.builtin.shell:
    cmd: docker container rm -fv $(docker ps -aq --filter label=image.key={{ item }})
    strip_empty_ends: false
  register: kill_outcome
  failed_when: false
  changed_when:
    - kill_outcome.rc != 0
  loop: "{{ image_keys }}"

- name: Remove images
  ansible.builtin.shell:
    cmd: docker image rm -f $(docker images -q --filter label=image.key={{ item }})
    strip_empty_ends: false
  register: remove_outcome
  failed_when: false
  changed_when:
    - remove_outcome.rc != 0
  loop: "{{ image_keys }}"
