---
- name: Lint, compile, analyze
  ansible.builtin.command:
    cmd: >-
      mvn clean
        enforcer:enforce
        spotless:check
        pmd:check
        compiler:compile
        spotbugs:check
        --activate-profiles {{ devenv }}
        --no-snapshot-updates
        --batch-mode
        --threads 2
      {% if maven_projects is defined %}
        --projects {{ maven_projects | map('regex_replace', '^', ':') | join(',') }}
      {% endif %}
    chdir: "{{ project.dir }}"
    strip_empty_ends: false
  changed_when: true
