---
- name: Capture CID
  ansible.builtin.command:
    cmd: git hash-object --stdin
    stdin: |
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=tool') }}
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=test') }}
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=baker') }}
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=stack/gear/' ~ devenv) }}
  register: stack_cid
  changed_when: false

- name: Declare tag
  ansible.builtin.set_fact:
    stack_tag: "{{ devenv }}-{{ stack_cid.stdout[:7] }}"

- name: Capture status
  ansible.builtin.command:
    cmd: docker {{ docker_entity }} inspect {{ image_ns }}/{{ gear.image }}:{{ stack_tag }}
  register: stack_status
  changed_when:
    - stack_status.rc != 0
  failed_when: false

- name: Status command
  ansible.builtin.debug:
    msg: "{{ stack_status.cmd|join(' ') }}"
  when: stack_status is changed

- name: Capture env
  ansible.builtin.command:
    cmd: test -f /.dockerenv
  register: is_docker_gear
  changed_when: false
  failed_when: false
