---
- name: Capture cid
  ansible.builtin.command:
    cmd: git hash-object --stdin
    stdin: |
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=tool') }}
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=test') }}
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=baker') }}
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=stack/gear/{{ devenv }}') }}
  register: stack_cid
  changed_when: false

- name: Declare tag
  ansible.builtin.set_fact:
    gear_tag: "{{ devenv }}-{{ stack_cid.stdout[:7] }}"

- name: Capture status
  ansible.builtin.command:
    cmd: docker {{ docker_entity }} inspect {{ image_ns }}/{{ gear.image }}:{{ gear_tag }}
  register: stack_status
  changed_when:
    - stack_status.rc != 0
  failed_when: false

- name: Status command
  ansible.builtin.debug:
    msg: "{{ stack_status.cmd|join(' ') }}"
  when: stack_status is changed
