---
- ansible.builtin.import_role:  # noqa: name[missing]
    name: image
  vars:
    image_tag: "{{ toolchain_tag }}"
    image_name: "{{ toolchain.image }}"
    image_home: "{{ stack_dir }}/{{ devenv }}"
    image_push: false
    image_args:
      DOCKER_VERSION: "{{ lookup('ansible.builtin.pipe', 'docker version --format {% raw %}{{.Client.Version}}{% endraw %}') }}"
