---
- ansible.builtin.import_role:  # noqa: name[missing]
    name: image
  vars:
    image_tag: "{{ toolchain_tag }}"
    image_name: "{{ toolchain.image }}"
    image_home: "{{ stack_dir }}"
    image_context: "{{ stack_dir }}/{{ devenv }}"
    image_push: "{{ image_storage != 'local' }}"
