version: '3'

set: [pipefail]

includes:
  basis:
    taskfile: basis/Taskfile.yml
    dir: basis
  toy:
    taskfile: toy/Taskfile.yml
    dir: toy
  func:
    taskfile: func/Taskfile.yml
    dir: func

vars:
  # basis
  STAND_BASIS_REVISION:
    sh: git write-tree --prefix=stands/basis
  STAND_BASIS_CID: '{{.STAND_BASIS_REVISION | trunc 7}}'
  STAND_BASIS_IMAGE: '{{.PROJECT_REPO}}/{{.PROJECT_NAME}}-stand-basis'
  STAND_BASIS_REF: '{{.STAND_BASIS_IMAGE}}:{{.STAND_BASIS_CID}}'
  # toy
  STAND_TOY_REVISION:
    sh: git write-tree --prefix=stands/toy
  STAND_TOY_CID: '{{.STAND_TOY_REVISION | trunc 7}}'
  STAND_TOY_IMAGE: '{{.PROJECT_REPO}}/{{.PROJECT_NAME}}-stand-toy'
  STAND_TOY_REF: '{{.STAND_TOY_IMAGE}}:{{.STAND_TOY_CID}}'
  # func
  STAND_FUNC_REVISION:
    sh: git write-tree --prefix=stands/func
  STAND_FUNC_CID: '{{.STAND_FUNC_REVISION | trunc 7}}'
  STAND_FUNC_IMAGE: '{{.PROJECT_REPO}}/{{.PROJECT_NAME}}-stand-func'
  STAND_FUNC_REF: '{{.STAND_FUNC_IMAGE}}:{{.STAND_FUNC_CID}}'
  # usage
  STAND_USAGE_REFS: >
    {{- if eq .USAGE "toy" -}}
      {{.STAND_BASIS_REF}} {{.STAND_TOY_REF}}
    {{- else if eq .USAGE "func" -}}
      {{.STAND_BASIS_REF}} {{.STAND_FUNC_REF}}
    {{- else -}}
      {{fail}}
    {{- end -}}

env:
  SCHEMA_CID: '{{.SCHEMA_PG_CID}}'
  SCHEMA_IMAGE: '{{.SCHEMA_PG_IMAGE}}'
  SCHEMA_REF: '{{.SCHEMA_PG_REF}}'
  FOO_CID: '{{.APP_FOO_CID}}'
  FOO_IMAGE: '{{.APP_FOO_IMAGE}}'
  FOO_REF: '{{.APP_FOO_REF}}'
  PROPS_COMBO: '{{.PROPS}}'

tasks:
  images:
    run: once
    internal: true
    cmds:
      - task: :stand:basis:image
      - task: :stand:toy:image
      - task: :stand:func:image
  run:
    run: once
    cmds:
#      - task: :lib:schema:image
      - task: :schema:postgres:image
      - task: :app:foo:image
      - task: :stand:basis:image
      - task: :stand:{{.USAGE}}:image
      - task: wipe-db
      - cmd: >
          docker compose
          --file basis/compose.yml
          --file {{.USAGE}}/compose.yml
          --profile {{.PROPS}}
          up
          --remove-orphans
          --quiet-pull
          --detach
  wipe:
    run: once
    aliases: [rm, prune, down]
    cmds:
      - cmd: >
          docker compose
          --file basis/compose.yml
          --file {{.USAGE}}/compose.yml
          --profile {{.PROPS}}
          down
          --volumes
  wipe-db:
    run: once
    internal: true
    status:
      - docker inspect schema-owner-{{.SCHEMA_PG_CID}}
    cmds:
      - docker rm -f env-db
