version: '3'

set: [pipefail]

includes:
  toy:
    taskfile: toy/Taskfile.yml
    dir: toy

env:
  SCHEMA_CID: '{{.LIB_SCHEMA_CID}}'
  SCHEMA_IMAGE: '{{.LIB_SCHEMA_IMAGE}}'
  SCHEMA_REPO: '{{.LIB_SCHEMA_REPO}}'
  SCHEMA_REF: '{{.LIB_SCHEMA_REF}}'
  FOO_CID: '{{.APP_FOO_CID}}'
  FOO_IMAGE: '{{.APP_FOO_IMAGE}}'
  FOO_REPO: '{{.APP_FOO_REPO}}'
  FOO_REF: '{{.APP_FOO_REF}}'
  STAND_CONF: alfa

tasks:
  wipe:
    aliases: [rm, prune, down]
    cmds:
      - task: toy:wipe
  run:
    run: once
    cmds:
      - task: :lib:schema:image
      - task: :app:foo:image
      - cmd: >
          docker compose
          --file docker-compose.yml
          --file func/docker-compose.yml
          --profile {{.ENV_DB_VENDOR}}
          up
          --detach
