version: '3'

set: [pipefail]

vars:
  STAND_TYPE: '{{.STAND_TYPE | default "toy"}}'
  STAND_PROPS: '{{.STAND_PROPS | default "turing"}}'
  STAND_REVISION:
    sh: git write-tree --prefix=stands
  STAND_CID: '{{.STAND_REVISION | trunc 7}}'
  STAND_IMAGE: '{{.PROJECT}}-stand-{{.STAND_TYPE}}'
  STAND_REPO: '{{.PROJECT_REPO}}/{{.STAND_IMAGE}}'
  STAND_REF: '{{.STAND_REPO}}:{{.STAND_CID}}'

env:
  SCHEMA_CID: '{{.LIB_SCHEMA_CID}}'
  SCHEMA_IMAGE: '{{.LIB_SCHEMA_IMAGE}}'
  SCHEMA_REPO: '{{.LIB_SCHEMA_REPO}}'
  SCHEMA_REF: '{{.LIB_SCHEMA_REF}}'
  FOO_CID: '{{.APP_FOO_CID}}'
  FOO_IMAGE: '{{.APP_FOO_IMAGE}}'
  FOO_REPO: '{{.APP_FOO_REPO}}'
  FOO_REF: '{{.APP_FOO_REF}}'
  PROPS_COMBO: '{{.STAND_PROPS}}'

tasks:
  image:
    run: once
    vars:
      COMMAND: '{{if eq .REGISTRY "localhost"}}inspect{{else}}pull{{end}}'
    status:
      - docker image {{.COMMAND}} {{.STAND_REF}}
    cmds:
      - task: reset
      - cmd: >
          docker build .
          -f Dockerfile
          -t {{.STAND_REF}}
  run:
    run: once
    cmds:
      - task: :lib:schema:image
      - task: :app:foo:image
      - task: image
      - task: wipe-db
      - cmd: >
          docker compose
          --file compose.yml
          --file types/compose.{{.STAND_TYPE}}.yml
          --profile {{.STAND_PROPS}}
          up
          --detach
  wipe:
    run: once
    aliases: [rm, prune, down]
    cmds:
      - cmd: >
          docker compose
          --file compose.yml
          --file types/compose.{{.STAND_TYPE}}.yml
          --profile {{.STAND_PROPS}}
          down
          --volumes
  wipe-db:
    run: once
    internal: true
    status:
      - docker inspect schema-owner-{{.LIB_SCHEMA_CID}}
    cmds:
      - docker rm -f env-db
  reset:
    run: once
    internal: true
    cmds:
      - cmd: docker rmi -f $(docker images -q -f reference={{.STAND_REPO}}) 2> /dev/null
        ignore_error: true
