---
name: Setup Docker
description: Setup Docker
inputs:
  token:
    description: Github token
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: >-
        sudo jq --arg user ${USER}
          '. += {"userns-remap": "$user"}' /etc/docker/daemon.json
          > /etc/docker/daemon.json
        cat /etc/docker/daemon.json
        sudo systemctl restart docker
    - uses: docker/setup-buildx-action@v3.0.0
    - uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
