---
name: Setup Docker
description: Setup Docker
inputs:
  token:
    description: Github token
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cat /etc/docker/daemon.json | jq -n '. + {"userns-remap": "runner"}' | sudo tee /etc/docker/daemon.json
        sudo sed -i -e "1i runner:$(id -u):1" /etc/subuid
        sudo sed -i -e "1i runner:$(getent group docker | cut -d: -f3):1" /etc/subgid
        sudo systemctl restart docker
    - uses: docker/setup-buildx-action@v3.0.0
    - uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
