---
name: Setup Docker
description: Setup Docker
inputs:
  token:
    description: Github token
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        jq -n '. + {"userns-remap": "runner"}' /etc/docker/daemon.json | sudo tee /etc/docker/daemon.json
        echo "runner:$(id -u):1" | sudo tee -a /etc/subuid
        echo "runner:$(getent group docker | cut -d: -f3):1" | sudo tee -a /etc/subgid
        sudo systemctl restart docker
    - uses: docker/setup-buildx-action@v3.0.0
    - uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
