version: '3'

set: [pipefail]

vars:
  SHARED_REVISION:
    sh: git write-tree --prefix=shared
  SHARED_REV: '{{.SHARED_REVISION | trunc 7 }}'

includes:
  schema:
    taskfile: schema/Taskfile.yml
    dir: schema

tasks:
  binary:
    status:
      - test -f target/pom-resolved-{{.SHARED_REV}}.xml
    cmds:
      - find . -name "pom-resolved*.xml" -type f -delete
      - mvn install -am -T1C -Drev={{.SHARED_REV}}
