version: '3'

tasks:
  image:
    run: once
    internal: true
    status:
      - docker {{.ENTITY}} inspect {{.STAND_FUNC_REF}}
    cmds:
      - task: ::docker:image:reset
        vars:
          IMAGE: '{{.STAND_FUNC_IMAGE}}'
      - cmd: >
          docker build .
          -f Dockerfile
          -t {{.STAND_FUNC_REF}}
      - task: ::docker:image:push
        vars:
          REF: '{{.STAND_FUNC_REF}}'
