---
- ansible.builtin.import_role:  # noqa: name[missing]
    name: image
    tasks_from: publish
  vars:
    image_source_tag: "tool/stacker:{{ devenv }}"
    image_target_tags:
      - "{{ image_ns }}/tool/stacker:{{ hostvars.stacker.package_tag }}"
