---
- name: Capture cid
  ansible.builtin.command:
    cmd: git hash-object --stdin
    stdin: |
      {{ dx_cid }}
      {{ env_cid }}
      {{ tool_cid }}
      {{ test_cid }}
  register: pipeline_cid
  changed_when: false

- name: Capture pipeline status
  ansible.builtin.command:
    cmd: docker {{ docker_entity }} inspect {{ pipeline_image }}:{{ pipeline_cid.stdout[:7] }}
  register: pipeline_status
  changed_when:
    - pipeline_status.rc != 0
  failed_when: false

- name: Pipeline status command
  ansible.builtin.debug:
    msg: "{{ pipeline_status.cmd|join(' ') }}"
  when: pipeline_status is changed
