---
- name: Binaries
  hosts: app
  run_once: true
  tasks:
    - name: Capture cid's
      ansible.builtin.command:
        cmd: git hash-object --stdin
        stdin: |
          {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=libs')[:7] }}
          {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=apps/' ~ app)[:7] }}
      # TODO: try to choose better name
      register: image_cid
      changed_when: false
      loop: "{{ solution.apps.values()|flatten|map(attribute='binary') }}"
      loop_control:
        loop_var: app
      tags: [always]
    - name: Declare cid's
      ansible.builtin.set_fact:
        image_cids: "{{ image_cid.results|items2dict(key_name='app', value_name='stdout') }}"
      tags: [always]
    - name: Capture statuses
      ansible.builtin.command:
        cmd: docker {{ docker_entity }} inspect {{ app.image }}:{{ image_cids[app.binary][:7] }}-{{ devenv }}
      register: image_status
      changed_when:
        - image_status.rc != 0
      failed_when: false
      loop: "{{ solution.apps.values()|flatten }}"
      loop_control:
        loop_var: app
        label: "{{ app.binary }}"
      tags: [always]
    - name: Status commands
      ansible.builtin.debug:
        msg: "{{ image_status.results|map(attribute='cmd')|map('join', ' ') }}"
      when: image_status is changed
      tags: [always]
    - name: Create binaries
      ansible.builtin.command:
        cmd: >
          mvn
          --no-snapshot-updates
          --fail-fast
          --batch-mode
          --threads 2
          --projects {{
            image_status.results
            | select('changed')
            | map(attribute='app.binary')
            | map('regex_replace', '^', ':')
            | join(',')
          }}
          --also-make
          clean
          {{ maven_phase | default('package') }}
          --define maven.compiler.release={{ dev[devenv].jdk.release }}
        chdir: "{{ playbook_dir }}/.."
        strip_empty_ends: false
      changed_when: true
      when: image_status is changed

- name: Binaries
  hosts: test
  run_once: true
  tasks:
    - name: Create binaries
      ansible.builtin.command:
        cmd: >
          mvn
          --no-snapshot-updates
          --batch-mode
          --projects tools,tests
          --also-make
          clean
          package
        chdir: "{{ playbook_dir }}/.."
        strip_empty_ends: false
      changed_when: true
