---
- import_playbook: sources.yml # noqa: name[play]
  tags: [sources, deps]

- name: Binaries
  hosts: lib
  tasks:
    - name: Capture status
      ansible.builtin.command:
        # todo: try to implement more lightweight check
        cmd: >
          mvn
          {% if is_local_building %}
          --offline
          {% endif %}
          dependency:get
          --define transitive=false
          --define artifact=org.smecalculus.bezmen:libs:{{ lib_version }}:pom
          {% if is_remote_building %}
          --define remoteRepositories=github::::https://maven.pkg.github.com/smecalculus/bezmen
          {% endif %}
        chdir: "{{ playbook_dir }}/../libs"
      register: binary_status
      changed_when: binary_status.rc != 0
      failed_when: false
    - name: Status command
      ansible.builtin.debug:
        msg: "{{ binary_status.cmd|join(' ') }}"
      when: binary_status is changed
    - name: Create binary
      ansible.builtin.command:
        cmd: >
          mvn
          --no-snapshot-updates
          --fail-fast
          --batch-mode
          --threads 2C
          --define revision={{ lib_version }}
          clean
          {% if is_local_building %}
          install
          {% else %}
          deploy
          {% endif %}
        chdir: "{{ playbook_dir }}/../libs"
      changed_when: true
      when: binary_status is changed

- name: Binaries
  hosts: app
  tasks:
    - name: Capture tag
      ansible.builtin.command:
        cmd: git hash-object --stdin
        stdin: |
          {{ lib_cid }}
          {{ app_cid }}
      register: image_tag
      changed_when: false
      tags: [always]
    - name: Capture status
      ansible.builtin.command:
        cmd: docker {{ docker_entity }} inspect {{ item.value }}:{{ image_tag.stdout[:7] }}
      register: image_status
      changed_when: image_status.rc != 0
      failed_when: false
      loop: "{{ app_images|dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      tags: [always]
    - name: Status commands
      ansible.builtin.debug:
        msg: "{{ image_status.results|map(attribute='cmd')|map('join', ' ') }}"
      when: image_status is changed
      tags: [always]
    - name: Create binary
      ansible.builtin.command:
        cmd: >
          mvn
          --no-snapshot-updates
          --fail-fast
          --batch-mode
          --threads 2C
          {% if not hostvars.lib.binary_status is changed %}
          --projects {{ image_status.results|select('changed')|map(attribute='item.key')|join(',') }}
          {% endif %}
          --define revision={{ app_version }}
          --define lib.version={{ lib_version }}
          clean
          verify
        chdir: "{{ playbook_dir }}/../apps"
        strip_empty_ends: false
      changed_when: true
      when: image_status is changed

- name: Coverage
  hosts: lib:app
  run_once: true
  tasks:
    - name: Generate reports
      ansible.builtin.command:
        cmd: >
          mvn
          --no-snapshot-updates
          --batch-mode
          clean
          antrun:run@units
          antrun:run@integrations
          antrun:run@overall
        chdir: "{{ playbook_dir }}/../tools"
        strip_empty_ends: false
      changed_when: true
      when: >
        hostvars.lib.binary_status is changed or
        hostvars.app.image_status is changed
