---
- import_playbook: sources.yml
  tags: deps

- hosts: lib
  tasks:
    - name: capture status
      command:
        cmd: >
          mvn dependency:get
          --define artifact=org.smecalculus.bezmen:libs:{{ lib_version }}:pom
          {% if is_building_local %}
          --offline
          {% endif %}
        chdir: ../libs
      register: binary_status
      changed_when: binary_status.rc != 0
      failed_when: false
      no_log: true
    - name: create binary
      command:
        cmd: >
          mvn clean
          {% if is_building_local %}
          install
          {% else %}
          deploy
          --settings settings.xml
          --define github.actor={{ github_actor }}
          --define github.token={{ github_token }}
          {% endif %}
          --define revision={{ lib_version }}
          --threads 2C
          --batch-mode
          --fail-fast
        chdir: ../libs
      when: binary_status is changed

- hosts: app
  tasks:
    - name: capture status
      command:
        cmd: docker {{ docker_entity }} inspect {{ docker_registry }}/{{ docker_repo }}/bezmen-app-{{ item }}:{{ app_cid }}
      register: image_status
      changed_when: image_status.rc != 0
      failed_when: false
      loop:
        - foo
    - name: create binary
      command:
        cmd: >
          mvn clean verify
          --projects {{ image_status.results|select('changed')|map(attribute='item')|join(',') }}
          --define revision={{ app_version }}
          --threads 2C
          --batch-mode
          --fail-fast
        chdir: ../apps
        strip_empty_ends: false
      when: >
        image_status is changed or
        hostvars.lib.binary_status is changed

- name: coverage
  hosts: lib:app
  run_once: true
  tasks:
    - name: create reports
      command:
        cmd: >
          mvn clean antrun:run@units antrun:run@integrations antrun:run@overall
        chdir: ../tools
        strip_empty_ends: false
      when: >
        hostvars.lib.binary_status is changed or
        hostvars.app.image_status is changed
