---
- import_playbook: sources.yml
  tags: deps

- name: binaries
  hosts: lib
  tasks:
    - name: capture status
      command:
        cmd: >
          mvn dependency:get
          --define artifact=org.smecalculus.bezmen:libs:{{ lib_version }}:pom
          --offline
        chdir: ../libs
      register: binary_status
      changed_when: binary_status.rc != 0
      failed_when: false
      no_log: true
    - name: create binary
      command:
        cmd: >
          mvn clean install
          --define revision={{ lib_version }}
          --threads 2C
          --batch-mode
          --fail-fast
        chdir: ../libs
      when: binary_status is changed

- name: binaries
  hosts: app
  tasks:
    - name: capture status
      command:
        cmd: test -f {{ item }}/target/app-{{ item }}-{{ app_version }}.jar
        chdir: ../apps
      register: app_status
      changed_when: app_status.rc != 0
      failed_when: false
      loop:
        - foo
    - name: create binary
      command:
        cmd: >
          mvn clean verify
          --projects {{ app_status.results|select('changed')|map(attribute='item')|join(',') }}
          --define libs.version={{ lib_version }}
          --define revision={{ app_version }}
          --threads 2C
          --batch-mode
          --also-make
          --fail-fast
        chdir: ../apps
        strip_empty_ends: false
      when: app_status is changed
