---
- import_playbook: binaries.yml   # noqa: name[play]
  vars:
    up_to_images: true
  tags: [binaries, deps]

- name: Images
  hosts: schema
  run_once: true
  tasks:
    - name: Capture statuses
      ansible.builtin.command:
        cmd: docker {{ docker_entity }} inspect {{ item.value }}:{{ schema_cid }}
      register: image_status
      changed_when: image_status.rc != 0
      failed_when: false
      loop: "{{ schema_images|dict2items }}"
      loop_control:
        label: "{{ item.key }}"
    - name: Status commands
      ansible.builtin.debug:
        msg: "{{ image_status.results|map(attribute='cmd')|map('join', ' ') }}"
      when: image_status is changed
    - name: Create images
      ansible.builtin.include_role:
        name: image
      vars:
        image_tag: "{{ schema_cid }}"
        image_name: "{{ item.value }}"
        image_home: "{{ playbook_dir }}/../schemas/{{ item.key }}"
        image_push: "{{ focus == 'solution' }}"
      loop: "{{ image_status.results|select('changed')|map(attribute='item') }}"

- name: Images
  hosts: app
  run_once: true
  tasks:
    - name: Create images
      ansible.builtin.include_role:
        name: image
      vars:
        image_tag: "{{ image_cid.stdout[:7] }}"
        image_name: "{{ item.value }}"
        image_home: "{{ playbook_dir }}/../apps/{{ item.key }}"
        image_context: target/docker-context
        image_push: "{{ focus == 'solution' }}"
      loop: "{{ image_status.results|select('changed')|map(attribute='item') }}"
      when: image_status is changed
