---
- import_playbook: images.yml  # noqa: name[play]
  tags: [images, deps]

- name: Solution
  hosts: solution
  run_once: true
  tasks:
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/pipeline/status.yml
      tags: [always]
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/solution/status.yml
      tags: [always]
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/solution/compile.yml
      tags: [compile]
      when: >
        solution_status is changed or
        pipeline_status is changed
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/solution/test.yml
      tags: [test]
      when: >
        solution_status is changed or
        pipeline_status is changed
    - ansible.builtin.import_tasks:  # noqa: name[missing]
        file: tasks/solution/package.yml
      tags: [package]
      when: solution_status is changed
