---
- name: Sources
  hosts: codebase
  run_once: true
  tasks:
    - name: Analyze
      ansible.builtin.command:
        cmd: >
          mvn
          --no-snapshot-updates
          --batch-mode
          {% if focus == 'solution' %}
          --projects libs,apps
          {% elif focus == 'pipeline' %}
          --projects tools,tests
          {% endif %}
          enforcer:enforce
          spotless:check
        chdir: "{{ playbook_dir }}/.."
        strip_empty_ends: false
      changed_when: false
    - name: Analyze
      ansible.builtin.command:
        # list all top level playbooks
        cmd: >
          ansible-lint
          sources.yml
          stacks.yml
        strip_empty_ends: false
      changed_when: false
      when: focus != 'solution'
    - name: Analyze
      ansible.builtin.command:
        cmd: yamllint ../.github
        strip_empty_ends: false
      changed_when: false
      when: focus != 'solution'
