---
- hosts: lib
  tasks:
    - name: lint
      command:
        cmd: >
          mvn
          {% if is_building_local %}
          spotless:apply
          {% else %}
          spotless:check
          --settings settings.xml
          --define github.actor={{ github_actor }}
          --define github.token={{ github_token }}
          {% endif %}
          --batch-mode
        chdir: ../libs
        strip_empty_ends: false
      changed_when: false

- hosts: app
  tasks:
    - name: lint
      command:
        cmd: >
          mvn
          {% if is_building_local %}
          spotless:apply
          {% else %}
          spotless:check
          --settings ../libs/settings.xml
          --define github.actor={{ github_actor }}
          --define github.token={{ github_token }}
          {% endif %}
          --define revision={{ app_version }}
          --batch-mode
        chdir: ../apps
        strip_empty_ends: false
      changed_when: false
