---
- hosts: lib
  tasks:
    - name: lint
      command:
        cmd: >
          mvn
          --no-snapshot-updates
          --batch-mode
          {% if is_local_building %}
          spotless:apply
          {% else %}
          spotless:check
          {% endif %}
        chdir: ../libs
        strip_empty_ends: false
      changed_when: false

- hosts: app
  tasks:
    - name: lint
      command:
        cmd: >
          mvn
          --no-snapshot-updates
          --batch-mode
          --define lib.version=LATEST
          {% if is_local_building %}
          spotless:apply
          {% else %}
          spotless:check
          {% endif %}
        chdir: ../apps
        strip_empty_ends: false
      changed_when: false

- hosts: test
  tasks:
    - name: lint
      command:
        cmd: >
          mvn
          --no-snapshot-updates
          --batch-mode
          --define lib.version=LATEST
          {% if is_local_building %}
          spotless:apply
          {% else %}
          spotless:check
          {% endif %}
        chdir: ../tests
        strip_empty_ends: false
      changed_when: false
