---
- name: Sources
  hosts: lib
  tasks:
    - name: Lint
      ansible.builtin.command:
        cmd: >
          mvn
          --no-snapshot-updates
          --batch-mode
          {% if is_local_building %}
          spotless:apply
          {% else %}
          spotless:check
          {% endif %}
        chdir: "{{ playbook_dir }}/../libs"
        strip_empty_ends: false
      changed_when: false

- name: Sources
  hosts: app
  tasks:
    - name: Lint
      ansible.builtin.command:
        cmd: >
          mvn
          --no-snapshot-updates
          --batch-mode
          --define lib.version=LATEST
          {% if is_local_building %}
          spotless:apply
          {% else %}
          spotless:check
          {% endif %}
        chdir: "{{ playbook_dir }}/../apps"
        strip_empty_ends: false
      changed_when: false

- name: Sources
  hosts: test
  tasks:
    - name: Lint
      ansible.builtin.command:
        cmd: >
          mvn
          --no-snapshot-updates
          --batch-mode
          --define lib.version=LATEST
          {% if is_local_building %}
          spotless:apply
          {% else %}
          spotless:check
          {% endif %}
        chdir: "{{ playbook_dir }}/../tests"
        strip_empty_ends: false
      changed_when: false

- name: Sources
  hosts: dx
  tasks:
    - name: Lint
      ansible.builtin.command:
        # list all top level playbooks
        cmd: >
          ansible-lint
          sources.yml
          stack.yml
          pipeline.yml
        strip_empty_ends: false
      changed_when: false
