---
- hosts: lib
  tasks:
    - command:
        cmd: >
          mvn
          --offline
          --batch-mode
          {% if is_local_building %}
          spotless:apply
          {% else %}
          spotless:check
          {% endif %}
        chdir: ../libs
        strip_empty_ends: false
      changed_when: false

- hosts: app
  tasks:
    # todo: можно инкапсулировать в pom.xml, привязав к фазе validate
    - command:
        cmd: >
          mvn
          --offline
          --batch-mode
          {% if is_local_building %}
          spotless:apply
          {% else %}
          spotless:check
          {% endif %}
          versions:set-property
          --define property=lib.version
          --define newVersion={{ lib_version }}
          --define generateBackupPoms=false
        chdir: ../apps
        strip_empty_ends: false
      changed_when: false

- hosts: test
  tasks:
    - command:
        cmd: >
          mvn
          --offline
          --batch-mode
          {% if is_local_building %}
          spotless:apply
          {% else %}
          spotless:check
          {% endif %}
          versions:set-property
          --define generateBackupPoms=false
          --define property=lib.version
          --define newVersion={{ lib_version }}
        chdir: ../tests
        strip_empty_ends: false
      changed_when: false
