---
- name: Sources
  hosts: lib
  run_once: true
  tasks:
    - name: Analyze
      ansible.builtin.command:
        cmd: >
          mvn
          --no-snapshot-updates
          --batch-mode
          enforcer:enforce
          spotless:check
        chdir: "{{ playbook_dir }}/../libs"
        strip_empty_ends: false
      changed_when: false

- name: Sources
  hosts: app
  run_once: true
  tasks:
    - name: Analyze
      ansible.builtin.command:
        cmd: >
          mvn
          --no-snapshot-updates
          --batch-mode
          spotless:check
        chdir: "{{ playbook_dir }}/../apps"
        strip_empty_ends: false
      changed_when: false

- name: Sources
  hosts: test
  run_once: true
  tasks:
    - name: Analyze
      ansible.builtin.command:
        cmd: >
          mvn
          --no-snapshot-updates
          --batch-mode
          spotless:check
        chdir: "{{ playbook_dir }}/../tests"
        strip_empty_ends: false
      changed_when: false

- name: Sources
  hosts: pipeline
  run_once: true
  tasks:
    - name: Analyze
      ansible.builtin.command:
        # list all top level playbooks
        cmd: >
          ansible-lint
          sources.yml
          systems.yml
        strip_empty_ends: false
      changed_when: false
    - name: Analyze
      ansible.builtin.command:
        cmd: yamllint ../.github
        strip_empty_ends: false
      changed_when: false
