---
- import_playbook: images.yml
  tags: deps

- hosts: app
  run_once: yes
  tasks:
    - name: capture stack status
      command:
        cmd: docker {{ docker_entity }} inspect {{ stack_image }}:{{ stack_cid }}
      register: stack_status
      changed_when: stack_status.rc != 0
      failed_when: false
      tags: [always]
    - name: stack status command
      debug:
        msg: "{{ stack_status.cmd|join(' ') }}"
      when: stack_status is changed
      tags: [always]
    - name: capture test status
      command:
        cmd: docker {{ docker_entity }} inspect {{ test_image }}:{{ test_cid }}
      register: test_status
      changed_when: test_status.rc != 0
      failed_when: false
      tags: [always]
    - name: test status command
      debug:
        msg: "{{ test_status.cmd|join(' ') }}"
      when: test_status is changed
      tags: [always]
    - block:
        - import_tasks:
            file: ../stacks/clean.yml
          tags: [compile]
        - import_tasks:
            file: ../stacks/compile.yml
          tags: [compile]
        - name: capture schema status
          command:
            cmd: docker inspect schema-owner-{{ schema_cid }}
          no_log: true
          register: schema_status
          changed_when: schema_status.rc != 0
          failed_when: false
          tags: [test]
        - name: wipe db if schema changed
          command:
            cmd: docker rm -f env-db
          when: schema_status is changed
          tags: [test]
        - name: run stack
          command:
            cmd: >
              docker compose
              --file compose.yml
              --profile {{ props }}
              up
              --remove-orphans
              --quiet-pull
              --no-deps
              --detach
            chdir: ../stacks/target/context
            strip_empty_ends: false
          tags: [test]
        - name: test stack
          command:
            cmd: >
              mvn clean test
              --projects {{ usage }}
              --define props.combo={{ props }}
              --batch-mode
              {% if reminder is defined %}
              --define bezmen.sharding.reminder={{ reminder }}
              {% endif %}
              {% if modulus is defined %}
              --define bezmen.sharding.modulus={{ modulus }}
              {% endif %}
              {% if not is_building_local %}
              --settings ../settings.xml
              --activate-profiles ci
              --define github.actor={{ github_actor }}
              --define github.token={{ github_token }}
              {% endif %}
            chdir: ../tests
            strip_empty_ends: false
          tags: [test]
        - import_tasks:
            file: ../stacks/package.yml
          tags: [package]
        - import_tasks:
            file: ../tests/package.yml
          tags: [package]
      when: >
        stack_status is changed or
        test_status is changed
