---
- import_playbook: images.yml
  tags: deps

- hosts: all
  run_once: yes
  tasks:
    - import_tasks:
        file: ../stacks/compile.yml
      tags: [compile]
    - import_tasks:
        file: ../stacks/status.yml
      tags: [status]
    - import_tasks:
        file: ../stacks/test.yml
      tags: [test]
      when: >
        stack_status is changed or
        test_status is changed
    - import_tasks:
        file: ../stacks/package.yml
      tags: [package]
      when: stack_status is changed
    - import_tasks:
        file: ../tests/package.yml
      tags: [package]
      when: test_status is changed
