---
- ansible.builtin.import_role:  # noqa: name[missing]
    name: image
    tasks_from: clean
  vars:
    image_keys: >-
      {{ hostvars.app.status.results
        | select('changed')
        | map(attribute='app')
        | map('regex_replace', '^(.*)$', 'app/\1/' ~ devenv)
      }}
