---
- name: Capture CID's
  ansible.builtin.command:
    cmd: git hash-object --stdin
    stdin: |
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=lib') }}
      {{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=app/' ~ app) }}
  register: cid
  changed_when: false
  loop: "{{ product.apps.keys() }}"
  loop_control:
    loop_var: app

- name: Declare tags
  ansible.builtin.set_fact:
    image_tags: >-
      {{ dict(cid.results
        | map(attribute='stdout')
        | map('truncate', 7, True, '')
        | map('regex_replace', '^', devenv ~ '-')
        | zip(cid.results|map(attribute='app'))
        | map('reverse'))
      }}
  changed_when: false

- name: Capture statuses
  ansible.builtin.command:
    cmd: docker {{ docker_entity }} inspect {{ image_ns }}/app/{{ app }}:{{ image_tags[app] }}
  register: status
  failed_when: false
  changed_when:
    - status.rc != 0
  loop: "{{ image_tags.keys() }}"
  loop_control:
    loop_var: app
    label: "{{ app }}:{{ image_tags[app] }}"
