---
- ansible.builtin.include_role:  # noqa: name[missing]
    name: image
    tasks_from: publish
  vars:
    image_source_tag: "app/{{ app }}:{{ devenv }}"
    image_target_tags:
      - "{{ image_ns }}/app/{{ app }}:{{ hostvars.app.image_tags[app] }}"
  loop: "{{ hostvars.app.image_status.results | select('changed') | map(attribute='app') }}"
  loop_control:
    loop_var: app
