version: '3'

set: [pipefail]

vars:
  APP_VERSION: 0.1.0

includes:
  foo:
    taskfile: foo/Taskfile.yml
    dir: foo

tasks:
  binaries:
    run: once
    deps:
      - task: foo:binary
  images:
    run: once
    deps:
      - task: foo:image
