version: '3'

set: [pipefail]

vars:
  APP_VERSION: 0.1.0
  # foo
  APP_FOO_REVISION:
    sh: git write-tree --prefix=apps/foo
  APP_FOO_CID: '{{.APP_FOO_REVISION | trunc 7}}'
  APP_FOO_VERSION: '{{.APP_VERSION}}-{{.APP_FOO_CID}}'
  APP_FOO_IMAGE: '{{.PROJECT_REPO}}/{{.PROJECT_NAME}}-app-foo'
  APP_FOO_REF: '{{.APP_FOO_IMAGE}}:{{.APP_FOO_CID}}'
  # usage
  APP_USAGE_SPEC: >
    {
      "toy": [
        "{{.APP_FOO_REF}}"
      ],
      "func": [
        "{{.APP_FOO_REF}}"
      ]
    }
  APP_USAGE_REFS: >
    {{- range index (mustFromJson .APP_USAGE_SPEC) .USAGE -}}
      {{.}}
    {{- end -}}

includes:
  foo:
    taskfile: foo/Taskfile.yml
    dir: foo

tasks:
  binaries:
    run: once
    deps:
      - task: foo:binary
  images:
    run: once
    deps:
      - task: foo:image
