version: '3'

set: [pipefail]

vars:
  APP_VERSION: 0.1.0

includes:
  foo:
    taskfile: foo/Taskfile.yml
    dir: foo

tasks:
  binary:
    deps:
      - task: foo:binary
  image:
    deps:
      - task: foo:image
