---
gear:
  image: stack/gear

product:
  name: "{{ project.name }}"
  image: stack/product
  config:
    file_name: "application.{{ config_exts[ops[opsenv].config.mapping_mode] }}"
    mapping_mode: "{{ ops[opsenv].config.mapping_mode }}"
  storages:
    postgres:
      image: "docker.io/library/postgres"
      dba:
        username: "postgres"
        password: "password"
      owner:
        username: "{{ project.name }}"
        password: "{{ project.name }}"
  databases:
    postgres:
      name: "{{ project.name }}"
      cid: "{{ lookup('ansible.builtin.pipe', 'git write-tree --prefix=db/postgres')[:7] }}"
      image: db/postgres
  schemas:
    postgres:
      - name: sepulkarium
  apps:
    java:
      - service: sepuling
        image: app/sepuling-java
        binary: sepuling-java
    kotlin:
      - service: sepuling
        image: app/sepuling-kotlin
        binary: sepuling-kotlin

config_exts:
  lightbend_config: conf
  spring_config: yaml
