---
gear:
  image: stack/gear

pipeline:
  image: stack/pipeline

product:
  image: stack/product
  storages:
    postgres:
      image: "docker.io/library/postgres"
      dba:
        username: "postgres"
        password: "password"
      owner:
        username: "{{ project.name }}"
        password: "{{ project.name }}"
  databases:
    postgres:
      name: enteropia
  schemas:
    postgres:
      name: sepulkarium
  apps:
    sepuling-java:
      service: sepuling
    sepuling-kotlin:
      service: sepuling
