---
gear:
  image: stack/gear

pipeline:
  image: stack/pipeline

product:
  name: "{{ project.name }}"
  image: stack/product
  config:
    file_name: "application.{{ config_exts[ops[opsenv].config.mapping_mode] }}"
    mapping_mode: "{{ ops[opsenv].config.mapping_mode }}"
  storages:
    postgres:
      image: "docker.io/library/postgres"
      dba:
        username: "postgres"
        password: "password"
      owner:
        username: "{{ project.name }}"
        password: "{{ project.name }}"
  databases:
    postgres:
      name: "{{ project.name }}"
  schemas:
    postgres:
      - name: sepulkarium
  apps:
    java:
      - service: sepuling
        name: sepuling-java
    kotlin:
      - service: sepuling
        name: sepuling-kotlin
  libs:
    - name: abstraction-client
    - name: messaging-client

config_exts:
  lightbend_config: conf
  spring_config: yaml
