version: '3'

set: [pipefail]

tasks:
  units:
    run: once
    cmds:
      - task: ::lib:units
      - task: ::app:units
  integrations:
    run: once
    cmds:
      - task: ::lib:integrations
      - task: ::app:integrations
  e2e:
    run: once
    status:
      - >
        for ref in {{.SCHEMA_USAGE_REFS}}; do
          docker {{.ENTITY}} inspect $ref-{{.STAGE_VERIFICATION_STATUS}}
        done
      - >
        for ref in {{.APP_USAGE_REFS}}; do
          docker {{.ENTITY}} inspect $ref-{{.STAGE_VERIFICATION_STATUS}}
        done
      - >
        for ref in {{.TEST_USAGE_REFS}}; do
          docker {{.ENTITY}} inspect $ref-{{.STAGE_VERIFICATION_STATUS}}
        done
      - >
        for ref in {{.STAND_USAGE_REFS}}; do
          docker {{.ENTITY}} inspect $ref-{{.STAGE_VERIFICATION_STATUS}}
        done
    cmds:
      - task: ::stand:run
      # TODO: ::lib:testing:binary
      - task: ::lib:binaries
      - task: ::test:run
