---
- name: Capture CID's
  ansible.builtin.command:
    cmd: git write-tree --prefix=db/{{ vendor }}
  register: image_cid
  changed_when: false
  loop: "{{ product.databases.keys() }}"
  loop_control:
    loop_var: vendor

- name: Declare tags
  ansible.builtin.set_fact:
    image_tags: >-
      {{ dict(image_cid.results
        | map(attribute='stdout')
        | map('truncate', 7, True, '')
        | zip(image_cid.results|map(attribute='vendor'))
        | map('reverse'))
      }}
  changed_when: false

- name: Capture statuses
  ansible.builtin.command:
    cmd: docker {{ docker_entity }} inspect {{ image_ns }}/db/{{ vendor }}:{{ image_tags[vendor] }}
  register: image_status
  failed_when: false
  changed_when:
    - image_status.rc != 0
  loop: "{{ image_tags.keys() }}"
  loop_control:
    loop_var: vendor
    label: "{{ vendor }}:{{ image_tags[vendor] }}"
