---
- ansible.builtin.include_role:  # noqa: name[missing]
    name: image
    tasks_from: publish
  vars:
    source_tag: "{{ db.image }}:{{ devenv }}"
    target_tags:
      - "{{ image_ns }}/{{ db.image }}:{{ db.cid }}"
  loop: "{{ hostvars.db.image_status.results|select('changed')|map(attribute='db') }}"
  loop_control:
    loop_var: db
    label: "{{ db.image }}"
