version: '3'

set: [pipefail]

includes:
  building:
    taskfile: building/Taskfile.yml
    dir: building
  testing:
    taskfile: testing/Taskfile.yml
    dir: testing
  verification:
    taskfile: verification/Taskfile.yml
    dir: verification
