= Решение

== Обмен сообщениями

Принимаем/отправляем сообщения в рамках некоторого протокола, отображая их в доменные объекты.

=== Протоколы

Wire protocol footnote:[Подробнее https://en.wikipedia.org/wiki/Wire_protocol] - протокол прикладного уровня, который используется для коммуникации между сервером и клиентом.

NOTE: Обычно используются стандартные протоколы, реже - кастомные.

==== HTTP

Протокол HTTP

==== JMX

Протокол JMX

=== Отображения

NOTE: Шаблон проектирования `Message Mapping`.

==== SpringMvc

Подробнее https://docs.spring.io/spring-framework/reference/web/webmvc.html

==== SpringManagement

Подробнее https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html

== Хранение состояния

Запоминаем/вспоминаем состояние в рамках некоторого протокола, отображая его в доменные объекты.

=== Протоколы

NOTE: Обычно используются кастомные протоколы, реже - стандартные.

==== PostgreSQL

Кастомный протокол PostgreSQL

=== Отображения

NOTE: Шаблон проектирования `Object-Relational Mapping`.

==== MyBatis

Подробнее https://mybatis.org/mybatis-3

==== SpringData

Подробнее https://docs.spring.io/spring-data/jdbc/docs/current/reference/html
