---
name: Beyond doubt

on:
  merge_group:
    branches:
      - main
  # for the sake of testing
  pull_request:
    branches:
      - test
  workflow_dispatch:

env:
  BINARY_STORAGE: maven.pkg.github.com
  IMAGE_STORAGE: ghcr.io

jobs:
  up-to-images:
    name: Up to images (${{ matrix.env.dev }})
    timeout-minutes: 10
    permissions:
      checks: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        env:
          - dev: godel
            os: ubuntu-20.04
          - dev: turing
            os: ubuntu-22.04
          - dev: church
            os: ubuntu-22.04
    runs-on: ${{ matrix.env.os }}
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: ./.github/actions/prepare
        with:
          devenv: ${{ matrix.env.dev }}
          tools: python java docker
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: ansible-playbook codebase.yaml
        working-directory: bakers/ansible
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: images
        run: >-
          ansible-playbook binaries.yaml
          -e binary_storage=${{ env.BINARY_STORAGE }}
          -e image_storage=${{ env.IMAGE_STORAGE }}
          -e devenv=${{ matrix.env.dev }}
        working-directory: bakers/ansible
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: mikepenz/action-junit-report@v4.0.3
        if: ${{ !cancelled() && (steps.images.outcome == 'success' || steps.images.outcome == 'failure') }}
        with:
          check_name: Unit test report
          report_paths: "**/target/surefire-reports/TEST-*.xml"
          require_tests: "${{ steps.images.outcome == 'failure' }}"
          fail_on_failure: false
          job_summary: false
      - uses: mikepenz/action-junit-report@v4.0.3
        if: ${{ !cancelled() && (steps.images.outcome == 'success' || steps.images.outcome == 'failure') }}
        with:
          check_name: Integration test report
          report_paths: "**/target/failsafe-reports/TEST-*.xml"
          require_tests: "${{ steps.images.outcome == 'failure' }}"
          fail_on_failure: false
          job_summary: false
      - name: Always empty E2E test report. See https://github.com/orgs/community/discussions/13690
        uses: mikepenz/action-junit-report@v4.0.3
        if: ${{ !cancelled() }}
        with:
          check_name: E2E test report
          require_tests: false
          fail_on_failure: false
          job_summary: false
