name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  binaries-and-images:
    name: Binaries & Images
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      checks: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: >
          ansible-playbook images.yml
          -e docker_registry=${{ env.REGISTRY }}
        working-directory: .dx

      - uses: EnricoMi/publish-unit-test-result-action@v2.7.0
        if: always()
        with:
          check_name: Unit Test Report
          check_run_annotations: none
          compare_to_earlier_commit: false
          action_fail_on_inconclusive: true
          action_fail: true
          job_summary: false
          comment_mode: always
          files: |
            libs/*/target/surefire-reports/TEST-*.xml
            apps/*/target/surefire-reports/TEST-*.xml
      - uses: madrapps/jacoco-report@v1.3
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          title: Unit Coverage Report
          update-comment: true
          token: ${{ secrets.GITHUB_TOKEN }}
          paths: >
            apps/foo/target/site/jacoco/jacoco.xml
      - uses: actions/upload-artifact@v3.1.2
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          name: unit-coverage-report
          path: |
            apps/foo/target/site/jacoco/jacoco.xml

      - uses: EnricoMi/publish-unit-test-result-action@v2.7.0
        if: always()
        with:
          check_name: Integration Test Report
          check_run_annotations: none
          compare_to_earlier_commit: false
          action_fail_on_inconclusive: true
          action_fail: true
          job_summary: false
          comment_mode: always
          files: |
            libs/*/target/failsafe-reports/TEST-*.xml
            apps/*/target/failsafe-reports/TEST-*.xml
      - uses: madrapps/jacoco-report@v1.3
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          title: Integration Coverage Report
          update-comment: true
          token: ${{ secrets.GITHUB_TOKEN }}
          paths: >
            apps/foo/target/site/jacoco-it/jacoco.xml
      - uses: actions/upload-artifact@v3.1.2
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          name: integration-coverage-report
          path: |
            apps/foo/target/site/jacoco-it/jacoco.xml

  stack-compiling:
    name: Stack Compiling
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [binaries-and-images]
    strategy:
      fail-fast: true
      matrix:
        usage: [func]
        props: [turing, church]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: >
          ansible-playbook stacks.yml -t compile
          -e usage=${{ matrix.usage }}
          -e props=${{ matrix.props }}
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: stack-${{ matrix.usage }}-${{ matrix.props }}
          path: stacks/target/context

  stack-testing:
    name: Stack Testing
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [stack-compiling]
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        usage: [func]
        props: [turing, church]
        shard: [0, 1]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v3.0.2
        with:
          name: stack-${{ matrix.usage }}-${{ matrix.props }}
      - run: ls -R
      - run: >
          ansible-playbook stacks.yml -t test
          -e docker_registry=${{ env.REGISTRY }}
          -e usage=${{ matrix.usage }}
          -e props=${{ matrix.props }}
          -e reminder=${{ matrix.shard }}
          -e modulus=2
        working-directory: .dx
      - uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: stack-test-report-${{ matrix.usage }}-${{ matrix.props }}-${{ matrix.shard }}
          path: tests/${{ matrix.usage }}/target/surefire-reports/*.xml
          # if-no-files-found: error

  stack-packaging:
    name: Stack Packaging
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [stack-testing]
    strategy:
      fail-fast: true
      matrix:
        usage: [func]
        props: [turing, church]
    permissions:
      checks: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/download-artifact@v3.0.2
        with:
          path: artifacts
      - run: ls -R
      - uses: EnricoMi/publish-unit-test-result-action@v2.7.0
        with:
          check_name: Stack Test Report (${{ matrix.usage }}, ${{ matrix.props }})
          check_run_annotations: none
          compare_to_earlier_commit: false
          action_fail_on_inconclusive: true
          action_fail: true
          job_summary: false
          comment_mode: always
          files: artifacts/stack-test-report-*/**/TEST-*.xml
      - uses: madrapps/jacoco-report@v1.3
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          title: Overall Coverage Report
          update-comment: true
          min-coverage-changed-files: 50
          token: ${{ secrets.GITHUB_TOKEN }}
          paths: >
            artifacts/apps/foo/target/site/jacoco/jacoco.xml
            artifacts/apps/foo/target/site/jacoco-it/jacoco.xml
