---
name: Convincing

on:
  merge_group:
    branches:
      - feature/**
      - bugfix/**
      - chore/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  uu-to-images:
    name: Up to images
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      packages: write
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: ./.github/actions/prepare
        with:
          tools: python java docker
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: ansible-playbook codebase.yaml
        working-directory: .dx
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: images
        run: >
          ansible-playbook images.yaml
          -e binary_repo=maven.pkg.github.com
          -e image_repo=ghcr.io
        working-directory: .dx
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: mikepenz/action-junit-report@v4
        if: ${{ !cancelled() && (steps.images.outcome == 'success' || steps.images.outcome == 'failure') }}
        with:
          check_name: Unit test report
          report_paths: "**/target/surefire-reports/TEST-*.xml"
          require_tests: "${{ steps.images.outcome == 'failure' }}"
          fail_on_failure: false
          job_summary: false
      - uses: mikepenz/action-junit-report@v4
        if: ${{ !cancelled() && (steps.images.outcome == 'success' || steps.images.outcome == 'failure') }}
        with:
          check_name: Integration test report
          report_paths: "**/target/failsafe-reports/TEST-*.xml"
          require_tests: "${{ steps.images.outcome == 'failure' }}"
          fail_on_failure: false
          job_summary: false
      - name: Always empty E2E test report. See https://github.com/orgs/community/discussions/13690
        uses: mikepenz/action-junit-report@v4
        if: ${{ !cancelled() }}
        with:
          check_name: E2E test report
          require_tests: false
          fail_on_failure: false
          job_summary: false
      - uses: actions/upload-artifact@v3.1.3
        if: ${{ !cancelled() }}
        with:
          name: test-coverage-report
          path: tools/target/coverage
          if-no-files-found: ignore
