---
name: Convincing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: stack/gear

jobs:
  up-to-images:
    name: Up to images (${{ matrix.env.dev }})
    timeout-minutes: 10
    permissions:
      checks: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        env:
          - dev: turing
            os: ubuntu-22.04
    runs-on: ${{ matrix.env.os }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run setup-docker
        uses: ./.github/actions/setup-docker
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ env.IMAGE_NAME }}/${{ matrix.env.dev }}
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.env.dev }}
          load: true
          cache-from: type=gha,scope=${{ env.IMAGE_NAME }}/${{ matrix.env.dev }}
          cache-to: type=gha,mode=max,scope=${{ env.IMAGE_NAME }}/${{ matrix.env.dev }}
      - name: Run setup-maven
        uses: ./.github/actions/setup-maven
      - name: Run ansible-playbook codebase.yaml
        run: >-
          docker run --rm
          --volume $(pwd):$(pwd)
          --volume ~/.m2:/root/.m2
          --workdir $(pwd)/bakers/ansible
          ${{ env.IMAGE_NAME }}:${{ matrix.env.dev }}
          ansible-playbook codebase.yaml
          -e devenv=${{ matrix.env.dev }}
      - name: Run ansible-playbook images.yaml
        id: images
        run: >-
          docker run --rm
          --volume $(pwd):$(pwd)
          --volume ~/.m2:/root/.m2
          --volume /var/run/docker.sock:/var/run/docker.sock
          --volume ~/.docker/config.json:/root/.docker/config.json:ro
          --env GITHUB_ACTOR=${{ github.actor }}
          --env GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          --workdir $(pwd)/bakers/ansible
          ${{ env.IMAGE_NAME }}:${{ matrix.env.dev }}
          ansible-playbook images.yaml -v
          -e devenv=${{ matrix.env.dev }}
          -e binary_storage=maven.pkg.github.com
          -e image_storage=ghcr.io
      - uses: mikepenz/action-junit-report@v4.1.0
        if: ${{ !cancelled() && (steps.images.outcome == 'success' || steps.images.outcome == 'failure') }}
        with:
          check_name: Unit test report
          report_paths: "**/target/surefire-reports/TEST-*.xml"
          require_tests: "${{ steps.images.outcome == 'failure' }}"
          fail_on_failure: false
          job_summary: false
      - uses: mikepenz/action-junit-report@v4.1.0
        if: ${{ !cancelled() && (steps.images.outcome == 'success' || steps.images.outcome == 'failure') }}
        with:
          check_name: Integration test report
          report_paths: "**/target/failsafe-reports/TEST-*.xml"
          require_tests: "${{ steps.images.outcome == 'failure' }}"
          fail_on_failure: false
          job_summary: false
      - uses: actions/upload-artifact@v4.3.0
        if: ${{ !cancelled() }}
        with:
          name: test-coverage-report
          path: tools/target/coverage
          if-no-files-found: ignore

  everything-is-fine:
    name: Everything is fine
    needs: [up-to-images]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ always() }}
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled') }}
        run: |
          echo "::error::Something went wrong"
          exit 1
