name: Pipeline Beyond Doubt Check

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  stack:
    name: Stack (${{ matrix.environment.tooling }} env)
    strategy:
      matrix:
        environment:
          - os: ubuntu-22.04
            tooling: latest
          - os: ubuntu-20.04
            tooling: previous
    runs-on: ${{ matrix.environment.os }}
    timeout-minutes: 10
    permissions:
      checks: write
      packages: write
      pull-requests: write
    env:
      JACOCO_UNITS: tools/target/coverage/units/jacoco.xml
      JACOCO_INTEGRATIONS: tools/target/coverage/integrations/jacoco.xml
      JACOCO_OVERALL: tools/target/coverage/overall/jacoco.xml
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: ./.github/actions/prepare
        with:
          revision: ${{ matrix.environment.tooling }}
          tools: python java docker
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: >
          ansible-playbook stack.yml
          -e docker_registry=${{ env.REGISTRY }}
          -e usage=toy
          -e prefs=turing
        working-directory: .dx
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
