---
name: Sanity

on:
  pull_request:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  up-to-binaries:
    name: Up to binaries
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      packages: write
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5.1.0
        with:
          context: stacks/toolchain/turing
#          push: true
          load: true
          tags: local/smecalculus/bezmen/stack/toolchain:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: ansible-playbook toolchain.yaml
        working-directory: bakers/ansible
      - run: >-
          docker run --rm --workdir $(pwd)/bakers/ansible
          --volume ~/.m2:/root/.m2
          --volume $(pwd):$(pwd)
          local/smecalculus/bezmen/stack/toolchain:latest
          ansible-playbook codebase.yaml
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: binaries
        run: ansible-playbook binaries.yaml
        working-directory: bakers/ansible
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: mikepenz/action-junit-report@v4.1.0
        if: ${{ !cancelled() && (steps.binaries.outcome == 'success' || steps.binaries.outcome == 'failure') }}
        with:
          check_name: Unit test report
          report_paths: "**/target/surefire-reports/TEST-*.xml"
          require_tests: "${{ steps.binaries.outcome == 'failure' }}"
          fail_on_failure: false
          job_summary: false

  everything-is-fine:
    name: Everything is fine
    needs: [up-to-binaries]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ always() }}
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled') }}
        run: |
          echo "::error::Something went wrong"
          exit 1
