name: Solution Minimal Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  sources:
    name: Sources
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: ./.github/actions/prepare
        with:
          tools: python java
      - run: >
          ansible-playbook sources.yml
          --limit lib:app
          -e docker_registry=${{ env.REGISTRY }}
        working-directory: .dx
