---
name: Solution convincing

on:
  merge_group:
    branches:
      - feature/**
      - bugfix/**
      - chore/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  uu-to-images:
    name: Up to images
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: ./.github/actions/prepare
        with:
          tools: python java docker
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: ansible-playbook sources.yml -l lib:app
        working-directory: .dx
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: >
          ansible-playbook images.yml
          -e binary_repo=maven.pkg.github.com
          -e image_repo=ghcr.io
          -e focus=solution
        working-directory: .dx
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: EnricoMi/publish-unit-test-result-action@v2.9.0
        if: ${{ !cancelled() }}
        with:
          check_name: Unit Test Report
          check_run_annotations: none
          compare_to_earlier_commit: false
          action_fail_on_inconclusive: true
          action_fail: true
          job_summary: false
          comment_mode: off
          files: |
            libs/*/target/surefire-reports/TEST-*.xml
            apps/*/target/surefire-reports/TEST-*.xml
      - uses: EnricoMi/publish-unit-test-result-action@v2.9.0
        if: ${{ !cancelled() }}
        with:
          check_name: Integration Test Report
          check_run_annotations: none
          compare_to_earlier_commit: false
          action_fail_on_inconclusive: true
          action_fail: true
          job_summary: false
          comment_mode: off
          files: |
            libs/*/target/failsafe-reports/TEST-*.xml
            apps/*/target/failsafe-reports/TEST-*.xml
      - name: Always empty E2E test report. See https://github.com/orgs/community/discussions/13690
        uses: EnricoMi/publish-unit-test-result-action@v2.9.0
        if: ${{ !cancelled() }}
        with:
          check_name: E2E Test Report
          check_run_annotations: none
          compare_to_earlier_commit: false
          action_fail_on_inconclusive: true
          action_fail: true
          job_summary: false
          comment_mode: off
          files: tests/*/target/surefire-reports/TEST-*.xml
      - uses: actions/upload-artifact@v3.1.3
        if: ${{ !cancelled() }}
        with:
          name: test-coverage-report
          path: .tools/target/coverage
          if-no-files-found: ignore
