name: Solution Beyond Doubt Check

on:
  push:
    branches: [foo]
  pull_request:
    branches: [foo]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io
  PYTHON: "3.9"

jobs:
  tooling:
    name: Tooling (ubuntu:${{ matrix.ubuntu }})
    strategy:
      matrix:
        ubuntu: ["22.04"]
    runs-on: ubuntu-${{ matrix.ubuntu }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ env.PYTHON }}
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: >
          ansible-playbook tooling.yml
        working-directory: .dx

  sources:
    name: Sources (java:${{ matrix.java }})
    strategy:
      matrix:
        java: ["17.0"]
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ env.PYTHON }}
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - run: >
          ansible-playbook sources.yml
          -e docker_registry=${{ env.REGISTRY }}
        working-directory: .dx
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  packages:
    name: Packages (java:${{ matrix.java }}, ubuntu:${{ matrix.ubuntu }})
    strategy:
      matrix:
        java: ["17.0"]
        ubuntu: ["22.04"]
    runs-on: ubuntu-${{ matrix.ubuntu }}
    timeout-minutes: 15
    permissions:
      checks: write
      packages: write
      pull-requests: write
    env:
      JACOCO_UNITS: tools/target/coverage/units/jacoco.xml
      JACOCO_INTEGRATIONS: tools/target/coverage/integrations/jacoco.xml
      JACOCO_OVERALL: tools/target/coverage/overall/jacoco.xml
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ env.PYTHON }}
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: >
          ansible-playbook images.yml
          -e docker_registry=${{ env.REGISTRY }}
        working-directory: .dx
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: EnricoMi/publish-unit-test-result-action@v2.9.0
        if: ${{ !cancelled() }}
        with:
          check_name: Unit Test Report
          check_run_annotations: none
          compare_to_earlier_commit: false
          action_fail_on_inconclusive: true
          action_fail: true
          job_summary: false
          comment_mode: off
          files: |
            libs/*/target/surefire-reports/TEST-*.xml
            apps/*/target/surefire-reports/TEST-*.xml
      - uses: EnricoMi/publish-unit-test-result-action@v2.9.0
        if: ${{ !cancelled() }}
        with:
          check_name: Integration Test Report
          check_run_annotations: none
          compare_to_earlier_commit: false
          action_fail_on_inconclusive: true
          action_fail: true
          job_summary: false
          comment_mode: off
          files: |
            libs/*/target/failsafe-reports/TEST-*.xml
            apps/*/target/failsafe-reports/TEST-*.xml
      - uses: madrapps/jacoco-report@v1.6
        if: ${{ github.event_name == 'pull_request' && hashFiles(env.JACOCO_UNITS) != '' }}
        with:
          title: Unit Coverage Report
          paths: ${{ env.JACOCO_UNITS }}
          token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
      - uses: madrapps/jacoco-report@v1.6
        if: ${{ github.event_name == 'pull_request' && hashFiles(env.JACOCO_INTEGRATIONS) != '' }}
        with:
          title: Integration Coverage Report
          paths: ${{ env.JACOCO_INTEGRATIONS }}
          token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
      - uses: madrapps/jacoco-report@v1.6
        if: ${{ github.event_name == 'pull_request' && hashFiles(env.JACOCO_OVERALL) != '' }}
        with:
          title: Overall Coverage Report
          paths: ${{ env.JACOCO_OVERALL }}
          token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true

  stack-compiling:
    strategy:
      fail-fast: false
      matrix:
        usage: [func]
        pref: [turing, church]
    name: Stack Compiling (usage:${{ matrix.usage }}, pref:${{ matrix.pref }})
    needs:
      - tooling
      - sources
      - packages
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ env.PYTHON }}
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: >
          ansible-playbook stack.yml
          -t compile
          -e docker_registry=${{ env.REGISTRY }}
          -e usage=${{ matrix.usage }}
          -e prefs=${{ matrix.pref }}
        working-directory: .dx
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: stack-${{ matrix.usage }}-${{ matrix.pref }}
          path: stacks/target/context
          if-no-files-found: error

  stack-testing:
    strategy:
      fail-fast: false
      matrix:
        usage: [func]
        pref: [turing, church]
        shard: [0, 1]
        java: ["17.0"]
        ubuntu: ["22.04"]
    name: >
      Stack Testing (usage:${{ matrix.usage }}, pref:${{ matrix.pref }}, shard:${{ matrix.shard }},
        java:${{ matrix.java }}, ubuntu:${{ matrix.ubuntu }})
    needs: [stack-compiling]
    timeout-minutes: 15
    runs-on: ubuntu-${{ matrix.ubuntu }}
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ env.PYTHON }}
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v3.0.2
        with:
          name: stack-${{ matrix.usage }}-${{ matrix.pref }}
          path: stacks/target/context
      - run: >
          ansible-playbook stack.yml
          -t test
          -e docker_registry=${{ env.REGISTRY }}
          -e usage=${{ matrix.usage }}
          -e prefs=${{ matrix.pref }}
          -e reminder=${{ matrix.shard }}
          -e modulus=2
        working-directory: .dx
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3.1.2
        if: ${{ !cancelled() }}
        with:
          name: e2e-test-report-${{ matrix.usage }}-${{ matrix.pref }}-${{ matrix.shard }}
          path: tests/e2e/target/surefire-reports/*.xml

  stack-packaging:
    strategy:
      fail-fast: false
      matrix:
        usage: [func]
        pref: [turing, church]
    name: Stack Packaging (usage:${{ matrix.usage }}, pref:${{ matrix.pref }})
    needs: [stack-testing]
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ env.PYTHON }}
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v3.0.2
        with:
          name: stack-${{ matrix.usage }}-${{ matrix.pref }}
          path: stacks/target/context
      - run: >
          ansible-playbook stack.yml
          -t package
          -e docker_registry=${{ env.REGISTRY }}
          -e usage=${{ matrix.usage }}
          -e prefs=${{ matrix.pref }}
        working-directory: .dx

  pipeline-packaging:
    name: Pipeline Packaging
    needs: [stack-testing]
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ env.PYTHON }}
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: >
          ansible-playbook pipeline.yml
          -e docker_registry=${{ env.REGISTRY }}
        working-directory: .dx

  stack-reporting:
    name: Stack Reporting
    needs: [stack-testing]
    if: ${{ !cancelled() && (needs.stack-testing.result == 'success' || needs.stack-testing.result == 'failure') }}
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      checks: write
    steps:
      - uses: actions/download-artifact@v3.0.2
        with:
          path: artifacts
      - run: ls -R
        working-directory: artifacts
      - uses: EnricoMi/publish-unit-test-result-action@v2.9.0
        with:
          check_name: E2E Test Report
          check_run_annotations: none
          compare_to_earlier_commit: false
          action_fail_on_inconclusive: true
          action_fail: true
          job_summary: false
          comment_mode: off
          files: artifacts/e2e-test-report-*/**/TEST-*.xml
