---
name: Solution sanity

on:
  pull_request:
    branches-ignore:
      - main
    paths:  # waiting for https://github.com/actions/runner/issues/2324
      - libs/**
      - apps/**
      - schemas/**
      - solutions/**
  workflow_dispatch:

jobs:
  up-to-binaries:
    name: Up to binaries
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      packages: write
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: ./.github/actions/prepare
        with:
          tools: python java
#      - run: ansible-playbook sources.yml -l lib:app
      - run: echo foo
        working-directory: .dx
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: binaries
        run: >
          ansible-playbook binaries.yml
          -e binary_repo=maven.pkg.github.com
          -e focus=solution
        working-directory: .dx
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: mikepenz/action-junit-report@v4
        if: ${{ !cancelled() }}
        with:
          check_name: Unit Test Report
          report_paths: "**/surefire-reports/TEST-*.xml"
          require_tests: "${{ steps.binaries.outcome == 'failure' }}"
          fail_on_failure: true
          job_summary: false
