---
name: Task change

on:
  push:
    branches:
      - task/**
  workflow_dispatch:

env:
  IMAGE_NAME: stack/gear

jobs:
  up-to-sources:
    name: Up to sources (${{ matrix.env.dev }})
    timeout-minutes: 5
    permissions:
      checks: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        env:
          - dev: turing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run setup-gear
        uses: ./.github/actions/setup-gear
        with:
          devenv: ${{ matrix.env.dev }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run ansible-playbook sources.yaml
        run: >-
          docker run --rm
          --volume $(pwd):$(pwd)
          --volume ~/.m2:/root/.m2
          --workdir $(pwd)/baker/ansible
          ${{ env.IMAGE_NAME }}:${{ matrix.env.dev }}
          ansible-playbook sources.yaml
          -e devenv=${{ matrix.env.dev }}

  everything-is-fine:
    name: Everything is fine
    needs: [up-to-sources]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ always() }}
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled') }}
        run: |
          echo "::error::Something went wrong"
          exit 1
