name: Toy

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  packages: write

jobs:
  playground:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ghcr.io/smecalculus/bezmen-stand-toy:3bfa587-verified
      - run: docker image pull ghcr.io/smecalculus/bezmen-schema-postgres:d187f2f-verified
