---
name: Work change

on:
  pull_request:
    branches: [main]
    types: [synchronize]
  workflow_dispatch:

env:
  IMAGE_NAME: stack/gear

jobs:
  up-to-images:
    name: Up to images (${{ matrix.env.dev }})
    timeout-minutes: 15
    permissions:
      checks: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        env:
          - dev: turing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Run setup-gear
        uses: ./.github/actions/setup-gear
        with:
          devenv: ${{ matrix.env.dev }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run ansible-playbook images.yaml
        id: images
        run: >-
          docker run --rm
          --volume $(pwd):$(pwd)
          --volume ~/.m2:/root/.m2
          --volume /var/run/docker.sock:/var/run/docker.sock
          --volume ~/.docker/config.json:/root/.docker/config.json:ro
          --env GITHUB_ACTOR=${{ github.actor }}
          --env GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          --workdir $(pwd)/orchestrator/ansible
          ${{ env.IMAGE_NAME }}:${{ matrix.env.dev }}
          ansible-playbook images.yaml -v
          -e devenv=${{ matrix.env.dev }}
          -e repo_mode=rw
      - uses: mikepenz/action-junit-report@v4.2.1
        if: ${{ !cancelled() && (steps.images.outcome == 'success' || steps.images.outcome == 'failure') }}
        with:
          check_name: Unit tests
          report_paths: "**/target/surefire-reports/TEST-*.xml"
          require_tests: "${{ steps.images.outcome == 'failure' }}"
          fail_on_failure: false
          job_summary: false
      - uses: mikepenz/action-junit-report@v4.2.1
        if: ${{ !cancelled() && (steps.images.outcome == 'success' || steps.images.outcome == 'failure') }}
        with:
          check_name: Integration tests
          report_paths: "**/target/failsafe-reports/TEST-*.xml"
          require_tests: "${{ steps.images.outcome == 'failure' }}"
          fail_on_failure: false
          job_summary: false
      - uses: actions/upload-artifact@v4.3.3
        if: ${{ !cancelled() }}
        with:
          name: test-coverage-report
          path: tool/target/coverage
          if-no-files-found: ignore

  everything-is-fine:
    name: Everything is fine
    needs: [up-to-images]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ always() }}
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled') }}
        run: |
          echo "::error::Something went wrong"
          exit 1
